import {useEffect,useMemo,useState} from "react";
import {NavLink} from "react-router-dom";
import AppShell,{Stat,Empty} from "../components/AppShell";
import {useAuth} from "../context/AuthContext";
import {supabase} from "../lib/supabase";

const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0});
const pct=n=>Math.round(Number(n||0)*100)/100;
function Card({children,className=""}){return <section className={"panel "+className}>{children}</section>}
function Head({kicker,title,text,action}){return <div className="panel-head"><div>{kicker&&<span className="section-kicker">{kicker}</span>}<h2>{title}</h2>{text&&<p>{text}</p>}</div>{action}</div>}

export function SellerCommandCenter(){
 const {session}=useAuth(); const [d,setD]=useState({orders:[],products:[],listings:[],stores:[]});
 useEffect(()=>{if(!session?.user?.id)return;const u=session.user.id;Promise.all([
  supabase.from("orders").select("*").eq("seller_id",u),
  supabase.from("products").select("*").eq("status","active"),
  supabase.from("listings").select("*").eq("seller_id",u),
  supabase.from("stores").select("*").eq("seller_id",u)
 ]).then(([o,p,l,s])=>setD({orders:o.data||[],products:p.data||[],listings:l.data||[],stores:s.data||[]}))},[session?.user?.id]);
 const revenue=d.orders.reduce((a,o)=>a+Number(o.amount||0),0), delivered=d.orders.filter(o=>o.status==="delivered").length;
 const margin=d.listings.reduce((a,l)=>a+Number(l.selling_price||0)-Number(l.cost_price||0),0);
 return <AppShell role="seller" title="Seller Command Center"><section className="hero-panel"><div><span className="hero-kicker">BUCKET INDIA · GROWTH OS</span><h2>Your store, your numbers, <span>one command center.</span></h2><p>Discover products, price with confidence, grow your Shopify stores and control fulfillment, money and risk from one workspace.</p><div className="hero-actions"><NavLink className="btn primary" to="/seller/profit">Calculate profit ↗</NavLink><NavLink className="btn glass" to="/seller/reports">Open reports</NavLink></div></div><div className="hero-orb"><div>BI</div></div></section>
 <div className="stats modern-stats"><Stat label="Gross order value" value={money(revenue)} hint="All seller orders"/><Stat label="Estimated margin" value={money(margin)} hint="Catalog pricing spread"/><Stat label="Delivery rate" value={d.orders.length?Math.round(delivered/d.orders.length*100)+"%":"—"} hint="Delivered orders"/><Stat label="Store channels" value={d.stores.length} hint="Connected Shopify stores"/></div>
 <div className="growth-grid"><Card><Head kicker="SELL MORE" title="Product intelligence" text="Turn vendor inventory into launch-ready offers."/><div className="quick-grid">{[["Product Marketplace","Browse vendor products","/seller/products","↗"],["Profit Calculator","Know net profit before pushing","/seller/profit","₹"],["Winning Products","Track what deserves attention","/seller/winning-ads","✦"],["Shopify Stores","Manage connected channels","/seller/stores","◇"]].map(x=><NavLink className="feature-card" to={x[2]} key={x[0]}><span>{x[3]}</span><div><b>{x[0]}</b><p>{x[1]}</p></div><strong>→</strong></NavLink>)}</div></Card>
 <Card><Head kicker="BUSINESS HEALTH" title="Your progress" text="Complete the essentials to unlock a stronger operating base."/><div className="health-meter"><div><b>{Math.min(100,d.stores.length*25+d.listings.length?Math.min(100,25+d.stores.length*25+d.listings.length*5):10)}%</b><span>workspace readiness</span></div><div className="meter"><i style={{width:"62%"}}/></div></div><div className="achievement-list"><span>✓ Connect a Shopify store</span><span>✓ Add your first catalog product</span><span>○ Complete KYC</span><span>○ Reach 10 delivered orders</span></div></Card></div>
 <Card className="momentum-panel"><Head kicker="COMMAND SHORTCUTS" title="Everything important is one click away"/><div className="shortcut-grid">{[["Orders","Review pending orders","/seller/orders"],["Shipments","Track fulfillment","/seller/shipping"],["NDR","Resolve delivery issues","/seller/ndr"],["RTO","Reduce returns to origin","/seller/rto-intelligence"],["Wallet","See available money","/seller/wallet"],["KYC","Verify your business","/seller/kyc"],["Reports","Download business insights","/seller/reports"],["AI Insights","Turn data into actions","/seller/insights"]].map(x=><NavLink className="shortcut" to={x[2]} key={x[0]}><b>{x[0]}</b><span>{x[1]}</span> <strong>→</strong></NavLink>)}</div></Card></AppShell>
}

export function VendorCommandCenter(){
 const {session}=useAuth(); const [d,setD]=useState({vendor:null,products:[],orders:[]});
 const load=async()=>{if(!session?.user?.id)return;const {data:v}=await supabase.from("vendors").select("*").eq("owner_id",session.user.id).maybeSingle();if(!v)return setD({vendor:null,products:[],orders:[]});const [{data:p},{data:o}]=await Promise.all([supabase.from("products").select("*").eq("vendor_id",v.id),supabase.from("orders").select("*").eq("vendor_id",v.id)]);setD({vendor:v,products:p||[],orders:o||[]})};useEffect(()=>{load()},[session?.user?.id]);
 const gmv=d.orders.reduce((a,o)=>a+Number(o.amount||0),0),low=d.products.filter(p=>Number(p.stock||0)<10).length;
 return <AppShell role="vendor" title="Vendor Command Center"><section className="hero-panel"><div><span className="hero-kicker">BUCKET INDIA · SUPPLY OS</span><h2>Run your catalog, fulfillment and <span>seller network.</span></h2><p>Publish products at scale, import sheets, manage stock, fulfill seller orders and understand your supply business in real time.</p><div className="hero-actions"><NavLink className="btn primary" to="/vendor/import">Import products ↗</NavLink><NavLink className="btn glass" to="/vendor/reports">Open reports</NavLink></div></div><div className="hero-orb"><div>BI</div></div></section>
 <div className="stats modern-stats"><Stat label="Catalog products" value={d.products.length}/><Stat label="Live products" value={d.products.filter(p=>p.status==="active").length}/><Stat label="Order value" value={money(gmv)}/><Stat label="Low stock" value={low} hint="Below 10 units"/></div>
 <div className="growth-grid"><Card><Head kicker="SUPPLY COMMAND" title="Catalog at scale"/><div className="shortcut-grid">{[["Add product","Create a marketplace listing","/vendor/products"],["Import sheet","Bulk upload CSV/Excel-ready data","/vendor/import"],["Inventory","Watch stock and SKU health","/vendor/inventory"],["Sellers","Understand who sells you","/vendor/sellers"]].map(x=><NavLink className="shortcut" to={x[2]} key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><strong>→</strong></NavLink>)}</div></Card><Card><Head kicker="FULFILLMENT" title="Orders need attention"/><div className="pipeline">{["pending","confirmed","packed","shipped","delivered"].map(s=><div key={s}><b>{d.orders.filter(o=>o.status===s).length}</b><span>{s}</span></div>)}</div><NavLink className="btn secondary" to="/vendor/orders">Open fulfillment queue</NavLink></Card></div>
 <Card className="momentum-panel"><Head kicker="BUSINESS CONTROL" title="Operate like a modern supply platform"/><div className="shortcut-grid">{[["Shipping","Courier and fulfillment setup","/vendor/shipping"],["Wallet","Settlements and receivables","/vendor/wallet"],["KYC","Business verification","/vendor/kyc"],["Reports","Sales and inventory reports","/vendor/reports"],["NDR & RTO","Delivery exception intelligence","/vendor/exceptions"],["Integrations","APIs, webhooks and channels","/vendor/integrations"]].map(x=><NavLink className="shortcut" to={x[2]} key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><strong>→</strong></NavLink>)}</div></Card></AppShell>
}

export function ProfitCalculator(){
 const [f,setF]=useState({cost:500,sell:999,shipping:80,cod:30,gateway:20,rto:60,other:10});const set=(k,v)=>setF({...f,[k]:Number(v)});const gross=f.sell-f.cost;const net=gross-f.shipping-f.cod-f.gateway-f.rto-f.other;const margin=f.sell?net/f.sell*100:0;
 return <AppShell role="seller" title="Profit Intelligence"><div className="calculator-grid"><Card><Head kicker="UNIT ECONOMICS" title="Profit calculator" text="Model the real contribution before you push a product."/><div className="calc-fields">{Object.entries({cost:"Vendor cost",sell:"Selling price",shipping:"Shipping cost",cod:"COD fee",gateway:"Payment fee",rto:"Expected RTO cost",other:"Other costs"}).map(([k,l])=><label key={k}>{l}<input type="number" value={f[k]} onChange={e=>set(k,e.target.value)}/></label>)}</div></Card><Card className="profit-result"><span className="section-kicker">ESTIMATED NET PROFIT</span><strong>{money(net)}</strong><div className="profit-ring"><b>{pct(margin)}%</b><span>net margin</span></div><div className="result-lines"><span>Gross profit <b>{money(gross)}</b></span><span>Cost load <b>{money(f.sell-net)}</b></span><span>Break-even price <b>{money(f.cost+f.shipping+f.cod+f.gateway+f.rto+f.other)}</b></span></div><p>Use this simulator before setting seller margin or pushing to Shopify.</p></Card></div></AppShell>
}

export function KycCenter({role="seller"}){const {session}=useAuth();const [f,setF]=useState({entity_type:"business",legal_name:"",business_name:"",gstin:"",phone:"",address:"",pincode:""});const [row,setRow]=useState(null),[msg,setMsg]=useState("");useEffect(()=>{if(session?.user?.id)supabase.from("kyc_profiles").select("*").eq("user_id",session.user.id).maybeSingle().then(({data})=>{if(data){setRow(data);setF(data)}})},[session?.user?.id]);async function save(e){e.preventDefault();const payload={...f,user_id:session.user.id,completion:Math.min(100,[f.legal_name,f.business_name,f.gstin,f.phone,f.address,f.pincode].filter(Boolean).length/6*100,status:"submitted"};const q=row?supabase.from("kyc_profiles").update(payload).eq("user_id",session.user.id):supabase.from("kyc_profiles").insert(payload);const {error}=await q;setMsg(error?error.message:"KYC submitted for review.");if(!error)setRow({...payload})}return <AppShell role={role} title="KYC & Verification"><div className="kyc-head"><div><span className="section-kicker">TRUST CENTER</span><h2>Get your {role} account verified.</h2><p>Complete business and payout details once; use the same verified identity across operations.</p></div><div className="kyc-score"><b>{Math.round(row?.completion||0)}%</b><span>complete</span></div></div><Card><form className="form-stack" onSubmit={save}><div className="form-row"><label>Legal name<input value={f.legal_name||""} onChange={e=>setF({...f,legal_name:e.target.value})}/></label><label>Business / store name<input value={f.business_name||""} onChange={e=>setF({...f,business_name:e.target.value})}/></label></div><div className="form-row"><label>GSTIN<input value={f.gstin||""} onChange={e=>setF({...f,gstin:e.target.value})}/></label><label>Phone<input value={f.phone||""} onChange={e=>setF({...f,phone:e.target.value})}/></label></div><label>Business address<textarea rows="3" value={f.address||""} onChange={e=>setF({...f,address:e.target.value})}/></label><label>Pincode<input value={f.pincode||""} onChange={e=>setF({...f,pincode:e.target.value})}/></label><div className="kyc-docs"><span>✓ Identity details</span><span>✓ Business details</span><span>○ PAN document</span><span>○ Bank proof</span></div><button className="btn primary">Save & submit KYC</button>{msg&&<div className="alert success">{msg}</div>}</form></Card></AppShell>
}

export function WalletCenter({role="seller"}){const {session}=useAuth();const [w,setW]=useState({available_balance:0,pending_balance:0,hold_balance:0});const [tx,setTx]=useState([]);useEffect(()=>{if(!session?.user?.id)return;Promise.all([supabase.from("wallet_accounts").select("*").eq("user_id",session.user.id).maybeSingle(),supabase.from("wallet_transactions").select("*").eq("user_id",session.user.id).order("created_at",{ascending:false}).limit(20)]).then(([a,t])=>{setW(a.data||w);setTx(t.data||[])})},[session?.user?.id]);return <AppShell role={role} title="Wallet & Settlements"><div className="stats modern-stats"><Stat label="Available" value={money(w.available_balance)}/><Stat label="Pending" value={money(w.pending_balance)}/><Stat label="On hold" value={money(w.hold_balance)}/><Stat label="Total position" value={money(Number(w.available_balance)+Number(w.pending_balance)+Number(w.hold_balance))}/></div><div className="dashboard-grid"><Card><Head kicker="MONEY MOVEMENT" title="Transaction ledger" text="Every credit, debit and hold should be traceable."/><div className="mini-list">{tx.length?tx.map(x=><div className="list-item" key={x.id}><div><b>{x.description}</b><span>{new Date(x.created_at).toLocaleString("en-IN")}</span></div><strong className={x.type==="credit"?"ledger-credit":"ledger-debit"}>{x.type==="credit"?"+":"-"}{money(x.amount)}</strong></div>):<Empty title="Wallet is ready" text="Settlement transactions will appear here."/>}</div></Card><Card><Head kicker={role==="vendor"?"VENDOR SETTLEMENT":"SELLER MONEY"} title="Settlement rules"/><div className="rule-list"><span>Available balance → withdrawable</span><span>Pending balance → awaiting settlement</span><span>Hold balance → risk / exception reserve</span><span>COD margin → released after delivery and reconciliation</span></div></Card></div></AppShell>
}

export function ReportsCenter({role="seller"}){const {session}=useAuth();const [orders,setOrders]=useState([]);useEffect(()=>{if(!session?.user?.id)return;const q=role==="vendor"?supabase.from("orders").select("*").eq("vendor_id",session.user.id):supabase.from("orders").select("*").eq("seller_id",session.user.id);q.then(({data})=>setOrders(data||[]))},[session?.user?.id,role]);const total=orders.reduce((a,o)=>a+Number(o.amount||0),0),statuses=["pending","confirmed","packed","shipped","delivered","ndr","rto","cancelled"];return <AppShell role={role} title="Reports & Analytics"><div className="stats modern-stats"><Stat label="Orders" value={orders.length}/><Stat label="Order value" value={money(total)}/><Stat label="Delivered" value={orders.filter(o=>o.status==="delivered").length}/><Stat label="Exceptions" value={orders.filter(o=>["ndr","rto"].includes(o.status)).length}/></div><div className="dashboard-grid"><Card><Head kicker="ORDER FUNNEL" title="Fulfillment distribution"/><div className="bar-chart">{statuses.map(s=>{const n=orders.filter(o=>o.status===s).length;const h=orders.length?Math.max(8,n/orders.length*100):8;return <div className="bar-col" key={s}><div className="bar" style={{height:h+"%"}}/><b>{n}</b><span>{s}</span></div>})}</div></Card><Card><Head kicker="REPORT BUILDER" title="Export-ready views"/><div className="report-list">{["Sales summary","Product performance","Order status","Shipping performance","NDR / RTO","Wallet & settlements"].map(x=><div className="report-row" key={x}><div><b>{x}</b><span>Live data · filtered to your account</span></div><button className="btn secondary" onClick={()=>alert("Report export can be connected to CSV generation next.")}>Export</button></div>)}</div></Card></div></AppShell>
}

export function VendorImport(){
 const {session}=useAuth();const [rows,setRows]=useState([]),[msg,setMsg]=useState("");const sample="title,sku,category,description,cost_price,stock,image_url,status\nPortable Mini Blender,BI-1001,Kitchen,Rechargeable blender,499,100,https://example.com/blender.jpg,active\n";function download(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([sample],{type:"text/csv"}));a.download="bucket-india-product-sample.csv";a.click()}function parse(text){const [head,...lines]=text.trim().split(/\r?\n/);const keys=head.split(",").map(x=>x.trim());setRows(lines.filter(Boolean).map(line=>Object.fromEntries(line.split(",").map((v,i)=>[keys[i],v.trim()]))))}async function importRows(){const {data:v}=await supabase.from("vendors").select("id").eq("owner_id",session.user.id).maybeSingle();if(!v)return setMsg("Vendor profile not found.");const payload=rows.filter(r=>r.title).map(r=>({vendor_id:v.id,title:r.title,sku:r.sku||null,category:r.category||"General",description:r.description||null,cost_price:Number(r.cost_price||0),stock:Number(r.stock||0),image_url:r.image_url||null,status:r.status||"active"}));const {error}=await supabase.from("products").insert(payload);setMsg(error?error.message:payload.length+" products imported successfully.");if(!error)setRows([])}return <AppShell role="vendor" title="Import Products"><div className="import-hero"><div><span className="section-kicker">BULK CATALOG</span><h2>Upload once. Publish hundreds.</h2><p>Start with our sample sheet, prepare your catalog, preview rows and import into the vendor marketplace.</p></div><button className="btn primary" onClick={download}>Download sample CSV ↓</button></div><Card><div className="drop-zone"><input type="file" accept=".csv,.txt" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>parse(String(r.result));r.readAsText(f)}}}/><b>Drop your CSV here or choose a file</b><span>Columns: title, SKU, category, description, cost, stock, image URL, status</span></div>{rows.length>0&&<><div className="table-wrap"><table><thead><tr>{Object.keys(rows[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,8).map((r,i)=><tr key={i}>{Object.keys(rows[0]).map(k=><td key={k}>{r[k]}</td>)}</tr>)}</tbody></table></div><button className="btn primary" onClick={importRows}>Import {rows.length} products ↗</button></>}{msg&&<div className="alert success">{msg}</div>}</Card></AppShell>
}

export function FeaturePage({role,title,description,children}){return <AppShell role={role} title={title}><Card><Head kicker="BUCKET INDIA OS" title={title} text={description}/>{children||<div className="empty"><div className="empty-icon">✦</div><h3>Workspace ready</h3><p>This module is connected to the new platform architecture.</p></div>}</Card></AppShell>}
