import {useState} from "react";
import {useNavigate} from "react-router-dom";
import {supabase} from "../lib/supabase";
export default function Login(){
 const navigate=useNavigate(),[mode,setMode]=useState("login"),[role,setRole]=useState("seller"),[form,setForm]=useState({name:"",email:"",password:""}),[busy,setBusy]=useState(false),[message,setMessage]=useState({type:"",text:""});
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function submit(e){e.preventDefault();setBusy(true);setMessage({type:"",text:""});try{
  if(mode==="signup"){const {data,error}=await supabase.auth.signUp({email:form.email.trim(),password:form.password,options:{data:{full_name:form.name.trim(),requested_role:role}}});if(error)throw error;if(data.session)navigate(role==="vendor"?"/vendor":"/seller");else setMessage({type:"success",text:"Account created. Check your email if confirmation is enabled, then sign in."});}
  else{const {data,error}=await supabase.auth.signInWithPassword({email:form.email.trim(),password:form.password});if(error)throw error;const {data:profile}=await supabase.from("profiles").select("role").eq("id",data.user.id).maybeSingle();navigate(profile?.role==="vendor"?"/vendor":"/seller");}
 }catch(err){setMessage({type:"error",text:err.message||"Unable to continue"});}finally{setBusy(false);}}
 return <div className="auth-page"><div className="auth-brand"><span className="logo-mark large">B</span><div><strong>Bucket India</strong><span>Powering Indian dropshipping</span></div></div><div className="auth-card"><div className="auth-heading"><h1>{mode==="login"?"Welcome back":"Create your account"}</h1><p>{mode==="login"?"Sign in to manage your dropshipping business.":"Choose your workspace and start selling."}</p></div>{mode==="signup"&&<div className="role-picker"><button type="button" className={role==="seller"?"selected":""} onClick={()=>setRole("seller")}><b>Seller</b><span>Source products and sell in your store</span></button><button type="button" className={role==="vendor"?"selected":""} onClick={()=>setRole("vendor")}><b>Vendor</b><span>List products and fulfill seller orders</span></button></div>}<form onSubmit={submit} className="form-stack">{mode==="signup"&&<label>Full name<input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="Your name" required/></label>}<label>Email<input type="email" value={form.email} onChange={e=>set("email",e.target.value)} placeholder="you@example.com" required/></label><label>Password<input type="password" minLength="6" value={form.password} onChange={e=>set("password",e.target.value)} placeholder="At least 6 characters" required/></label>{message.text&&<div className={`alert ${message.type}`}>{message.text}</div>}<button className="btn primary" disabled={busy}>{busy?"Please wait…":mode==="login"?"Sign in":"Create account"}</button></form><button className="btn ghost full" onClick={()=>{setMode(mode==="login"?"signup":"login");setMessage({type:"",text:""})}}>{mode==="login"?"New to Bucket India? Create account":"Already have an account? Sign in"}</button></div><p className="auth-foot">Seller + Vendor marketplace · Secured by Supabase Auth</p></div>;
}
