import {useEffect,useMemo,useState} from "react";
import AppShell,{Empty,Stat} from "../components/AppShell";
import {useAuth} from "../context/AuthContext";
import {supabase} from "../lib/supabase";

const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const statusClass=s=>`status-pill ${s||""}`;
const sellerTabs=["all","pending","confirmed","packed","shipped","delivered","ndr","rto","cancelled"];
const vendorTabs=["all","confirmed","packed","shipped","ndr","delivered","rto","cancelled"];

function useOrders(role){
 const {session}=useAuth(); const [rows,setRows]=useState([]),[loading,setLoading]=useState(true);
 async function load(){
  if(!session?.user?.id)return;
  setLoading(true);
  let q=supabase.from("orders").select("*, listings(product_id, store_id), shipments(*), ndr_cases(*), remittances(*)").order("created_at",{ascending:false});
  if(role==="seller")q=q.eq("seller_id",session.user.id);else{
   const {data:v}=await supabase.from("vendors").select("id").eq("owner_id",session.user.id).maybeSingle();
   q=v?q.eq("vendor_id",v.id).neq("status","pending"):q.eq("vendor_id","00000000-0000-0000-0000-000000000000");
  }
  const {data,error}=await q; if(!error)setRows(data||[]); setLoading(false);
 }
 useEffect(()=>{load(); if(!session?.user?.id)return;
  const channel=supabase.channel(`bucket-${role}-orders-${session.user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"orders"},()=>load()).on("postgres_changes",{event:"*",schema:"public",table:"shipments"},()=>load()).on("postgres_changes",{event:"*",schema:"public",table:"ndr_cases"},()=>load()).subscribe();
  return()=>{supabase.removeChannel(channel)};
 },[session?.user?.id,role]);
 return {rows,loading,load};
}

function Filters({search,setSearch,tab,setTab,tabs}){
 return <div className="ops-toolbar"><div className="search-box">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search order, customer, phone, AWB"/></div><div className="status-tabs">{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t==="all"?"All":t.toUpperCase()}</button>)}</div></div>;
}
function OrderTable({rows,role,onChanged}){
 const [busy,setBusy]=useState(""); const {session}=useAuth();
 async function sellerConfirm(id){setBusy(id);const {error}=await supabase.from("orders").update({status:"confirmed"}).eq("id",id).eq("status","pending");setBusy("");if(error)alert(error.message);else onChanged();}
 async function vendorStatus(o,status){
  setBusy(o.id); let error=null;
  if(status==="shipped"){
   const ship={order_id:o.id,vendor_id:o.vendor_id,status:"shipped",courier:o.shipments?.[0]?.courier||null,awb:o.shipments?.[0]?.awb||null,shipped_at:new Date().toISOString()};
   ({error}=await supabase.from("shipments").upsert(ship,{onConflict:"order_id"}));
   if(!error)({error}=await supabase.from("orders").update({status:"shipped"}).eq("id",o.id));
  } else if(["delivered","rto"].includes(status)){
   const patch={status};
   ({error}=await supabase.from("orders").update(patch).eq("id",o.id));
   if(!error)await supabase.from("shipments").update({status,delivered_at:status==="delivered"?new Date().toISOString():null,rto_at:status==="rto"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("order_id",o.id);
  } else ({error}=await supabase.from("orders").update({status}).eq("id",o.id));
  setBusy("");if(error)alert(error.message);else onChanged();
 }
 return <div className="table-wrap ops-table-wrap"><table><thead><tr><th></th><th>Order</th><th>Date</th><th>Customer</th><th>Amount</th><th>Payment</th><th>Vendor / Courier</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}>
 <td><span className="row-dot"/></td><td><b>#{o.external_order_id||o.id.slice(0,8)}</b><small>{o.quantity} item{o.quantity>1?"s":""}</small></td><td>{new Date(o.created_at).toLocaleDateString("en-IN")}</td><td>{o.customer_name||"Customer"}<small>{o.customer_phone||"—"}</small></td><td><b>{money(o.amount)}</b><small>Margin {money(o.seller_margin)}</small></td><td><span className="badge">{(o.payment_method||"cod").toUpperCase()}</span></td><td>{o.shipments?.[0]?.courier||o.courier||"Vendor managed"}<small>{o.shipments?.[0]?.awb||o.awb||"AWB pending"}</small></td><td><span className={statusClass(o.status)}>{o.status}</span></td>
 <td>{role==="seller"&&o.status==="pending"?<button className="btn primary compact" disabled={busy===o.id} onClick={()=>sellerConfirm(o.id)}>{busy===o.id?"Confirming…":"Confirm"}</button>:role==="vendor"?<VendorAction o={o} busy={busy===o.id} onChange={s=>vendorStatus(o,s)}/>:<span className="muted">Synced</span>}</td>
 </tr>)}</tbody></table></div>;
}
function VendorAction({o,busy,onChange}){
 const next=o.status==="confirmed"?"packed":o.status==="packed"?"shipped":["shipped","ndr"].includes(o.status)?"delivered":o.status==="delivered"?"rto":null;
 return <div className="action-stack">{next&&<button className="btn primary compact" disabled={busy} onClick={()=>onChange(next)}>{busy?"Updating…":next==="shipped"?"Create shipment":"Mark "+next}</button>}{["shipped","ndr"].includes(o.status)&&<button className="btn danger compact" disabled={busy} onClick={()=>onChange("rto")}>RTO</button>}</div>;
}

export function SellerOrders(){const d=useOrders("seller"),[tab,setTab]=useState("all"),[search,setSearch]=useState("");
 const rows=useMemo(()=>d.rows.filter(o=>(tab==="all"||o.status===tab)&&((o.external_order_id||"")+" "+(o.customer_name||"")+" "+(o.customer_phone||"")+" "+(o.awb||"")+" "+(o.shipments?.[0]?.awb||"")).toLowerCase().includes(search.toLowerCase())),[d.rows,tab,search]);
 const stats=sellerOrderStats(d.rows); return <AppShell role="seller" title="Orders"><div className="ops-hero"><div><span className="section-kicker">SHOPIFY → SELLER → VENDOR</span><h2>One order timeline. <span>Two dashboards.</span></h2><p>Orders land as Pending, become vendor-visible after Seller confirmation, then shipment, NDR, RTO and remittance stay synchronized.</p></div><div className="ops-orbit">LIVE</div></div><div className="stats ops-stats"><Stat label="Pending confirmation" value={stats.pending}/><Stat label="Confirmed / processing" value={stats.processing}/><Stat label="NDR" value={stats.ndr}/><Stat label="RTO" value={stats.rto}/><Stat label="Margin remittance" value={money(stats.margin)}/></div><section className="panel"><Filters search={search} setSearch={setSearch} tab={tab} setTab={setTab} tabs={sellerTabs}/>{rows.length?<OrderTable rows={rows} role="seller" onChanged={d.load}/>:<Empty title={d.loading?"Loading orders…":"No matching orders"} text="Shopify-synced orders appear here. Pending orders require seller confirmation before the vendor sees them."/>}</section></AppShell>}

export function VendorOrders(){const d=useOrders("vendor"),[tab,setTab]=useState("all"),[search,setSearch]=useState("");const rows=useMemo(()=>d.rows.filter(o=>(tab==="all"||o.status===tab)&&((o.external_order_id||"")+" "+(o.customer_name||"")+" "+(o.customer_phone||"")+" "+(o.awb||"")+" "+(o.shipments?.[0]?.awb||"")).toLowerCase().includes(search.toLowerCase())),[d.rows,tab,search]);const stats=sellerOrderStats(d.rows);return <AppShell role="vendor" title="Orders"><div className="ops-hero vendor"><div><span className="section-kicker">VENDOR FULFILLMENT CONTROL</span><h2>Confirmed orders are <span>your queue.</span></h2><p>Only Seller-confirmed orders enter this workspace. Shipments, NDR, RTO and delivery events flow back to the seller in real time.</p></div><div className="ops-orbit">SYNC</div></div><div className="stats ops-stats"><Stat label="Confirmed queue" value={stats.confirmed}/><Stat label="In transit" value={stats.inTransit}/><Stat label="NDR" value={stats.ndr}/><Stat label="Delivered" value={stats.delivered}/><Stat label="COD margin due" value={money(stats.margin)}/></div><section className="panel"><Filters search={search} setSearch={setSearch} tab={tab} setTab={setTab} tabs={vendorTabs}/>{rows.length?<OrderTable rows={rows} role="vendor" onChanged={d.load}/>:<Empty title={d.loading?"Loading vendor queue…":"No orders in this queue"} text="A Seller must confirm an order before it becomes visible to the vendor."/>}</section></AppShell>}

export function ShipmentCenter({role="seller"}){const d=useOrders(role),[filter,setFilter]=useState("all");const shipments=d.rows.flatMap(o=>(o.shipments||[]).map(s=>({...s,order:o}))).filter(s=>filter==="all"||s.status===filter);async function updateShipment(s,status){if(role!=="vendor")return;const {error}=await supabase.from("shipments").update({status,updated_at:new Date().toISOString(),shipped_at:status==="shipped"?new Date().toISOString():s.shipped_at,delivered_at:status==="delivered"?new Date().toISOString():s.delivered_at,rto_at:status==="rto"?new Date().toISOString():s.rto_at}).eq("id",s.id);if(!error&&status==="delivered")await supabase.from("orders").update({status:"delivered"}).eq("id",s.order.id);if(!error&&status==="rto")await supabase.from("orders").update({status:"rto"}).eq("id",s.order.id);if(error)alert(error.message);else d.load()}return <AppShell role={role} title="Shipment"><section className="panel shipment-panel"><div className="panel-head"><div><span className="section-kicker">LIVE TRACKING</span><h2>Shipment control tower</h2><p>{role==="vendor"?"Vendor-managed shipping is the source of truth.":"Courier updates from the vendor are mirrored here."}</p></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All shipments</option>{["ready","booked","shipped","ndr","delivered","rto"].map(x=><option key={x}>{x}</option>)}</select></div>{shipments.length?<div className="shipment-grid">{shipments.map(s=><article className="shipment-card" key={s.id}><div className="shipment-top"><span className={statusClass(s.status)}>{s.status}</span><b>#{s.order.external_order_id||s.order.id.slice(0,8)}</b></div><h3>{s.courier||"Courier not assigned"}</h3><p>AWB <strong>{s.awb||"Pending"}</strong></p><div className="shipment-timeline"><i className={s.status!=="ready"?"done":""}>Booked</i><i className={["shipped","ndr","delivered","rto"].includes(s.status)?"done":""}>Shipped</i><i className={s.status==="delivered"?"done":""}>Delivered</i></div>{role==="vendor"&&<div className="shipment-actions">{s.status==="ready"&&<button className="btn primary compact" onClick={()=>updateShipment(s,"shipped")}>Ship</button>}{["shipped","ndr"].includes(s.status)&&<><button className="btn primary compact" onClick={()=>updateShipment(s,"delivered")}>Delivered</button><button className="btn danger compact" onClick={()=>updateShipment(s,"rto")}>RTO</button></>}</div>}</article>)}</div>:<Empty title="No shipments yet" text="Once a vendor books a shipment it will be mirrored here for the seller."/>}</section></AppShell>}

export function NdrCenter({role="seller"}){const d=useOrders(role),cases=d.rows.flatMap(o=>(o.ndr_cases||[]).map(n=>({...n,order:o})));async function addCase(o){if(role!=="vendor")return;const {error}=await supabase.from("ndr_cases").insert({order_id:o.id,shipment_id:o.shipments?.[0]?.id||null,reason:"Delivery attempt failed",next_action:"Contact customer and re-attempt"});if(error)alert(error.message);else{await supabase.from("shipments").update({status:"ndr",updated_at:new Date().toISOString()}).eq("order_id",o.id);await supabase.from("orders").update({status:"ndr"}).eq("id",o.id);d.load()}}async function resolve(n){const {error}=await supabase.from("ndr_cases").update({status:"resolved",resolved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",n.id);if(error)alert(error.message);else d.load()}return <AppShell role={role} title="NDR"><div className="stats ops-stats"><Stat label="Open NDR" value={cases.filter(x=>x.status==="open").length}/><Stat label="Actioned" value={cases.filter(x=>x.status==="actioned").length}/><Stat label="Resolved" value={cases.filter(x=>x.status==="resolved").length}/><Stat label="Failed" value={cases.filter(x=>x.status==="failed").length}/></div><section className="panel"><div className="panel-head"><div><span className="section-kicker">NON-DELIVERY RESPONSE</span><h2>Recover deliveries before RTO.</h2><p>Every failed attempt becomes an operational case shared with the seller.</p></div></div><div className="case-grid">{cases.map(n=><article className="case-card" key={n.id}><span className={statusClass(n.status)}>{n.status}</span><h3>#{n.order.external_order_id||n.order.id.slice(0,8)}</h3><p>{n.reason||"Delivery attempt failed"}</p><small>{n.next_action||"Follow up with customer"}</small>{role==="vendor"&&n.status!=="resolved"&&<button className="btn primary compact" onClick={()=>resolve(n)}>Resolve case</button>}</article>)}{role==="vendor"&&d.rows.filter(o=>["shipped","ndr"].includes(o.status)&&!(o.ndr_cases||[]).some(n=>n.status==="open")).map(o=><article className="case-card create" key={o.id}><span>ATTENTION</span><h3>#{o.external_order_id||o.id.slice(0,8)}</h3><p>Mark a failed delivery attempt and start NDR follow-up.</p><button className="btn primary compact" onClick={()=>addCase(o)}>Create NDR case</button></article>)}</div>{!cases.length&&role==="seller"&&<Empty title="No NDR cases" text="Vendor delivery exceptions will appear here."/>}</section></AppShell>}

export function RtoCenter({role="seller"}){const d=useOrders(role);const rows=d.rows.filter(o=>o.status==="rto");return <AppShell role={role} title="RTO Intelligence"><section className="ops-hero risk"><div><span className="section-kicker">RETURN TO ORIGIN</span><h2>Turn RTO into <span>actionable data.</span></h2><p>See every returning parcel, its value, margin impact and courier trail in one place.</p></div><div className="ops-orbit">RTO</div></section><div className="stats ops-stats"><Stat label="RTO parcels" value={rows.length}/><Stat label="RTO GMV" value={money(rows.reduce((a,o)=>a+Number(o.amount||0),0))}/><Stat label="Margin at risk" value={money(rows.reduce((a,o)=>a+Number(o.seller_margin||0),0))}/></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Amount</th><th>Margin impact</th><th>Courier</th><th>AWB</th><th>RTO date</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td>#{o.external_order_id||o.id.slice(0,8)}</td><td>{o.customer_name||"—"}</td><td>{money(o.amount)}</td><td className="danger-text">{money(o.seller_margin)}</td><td>{o.shipments?.[0]?.courier||"—"}</td><td>{o.shipments?.[0]?.awb||o.awb||"—"}</td><td>{o.rto_at?new Date(o.rto_at).toLocaleDateString("en-IN"):"—"}</td></tr>)}</tbody></table></div>{!rows.length&&<Empty title="No RTO parcels" text="RTO orders will automatically appear here after vendor updates the shipment."/>}</section></AppShell>}

export function RemittanceCenter({role="seller"}){const {session}=useAuth();const [rows,setRows]=useState([]);async function load(){if(!session?.user?.id)return;let q=supabase.from("remittances").select("*, orders(external_order_id,amount,payment_method,seller_margin,customer_name)").order("created_at",{ascending:false});if(role==="seller")q=q.eq("seller_id",session.user.id);else{const {data:v}=await supabase.from("vendors").select("id").eq("owner_id",session.user.id).maybeSingle();q=v?q.eq("vendor_id",v.id):q.eq("vendor_id","00000000-0000-0000-0000-000000000000")}const {data,error}=await q;if(!error)setRows(data||[])}useEffect(()=>{load()},[session?.user?.id,role]);const total=rows.reduce((a,r)=>a+Number(r.amount||0),0);return <AppShell role={role} title="Margin Remittance"><section className="ops-hero finance"><div><span className="section-kicker">COD SETTLEMENT</span><h2>Vendor collects COD. <span>Seller margin is remitted.</span></h2><p>For delivered COD orders, the platform records the seller margin as a remittance obligation. Payment status stays visible to both parties.</p></div><div className="ops-orbit">₹</div></section><div className="stats ops-stats"><Stat label="Remittances" value={rows.length}/><Stat label="Total margin" value={money(total)}/><Stat label="Pending" value={money(rows.filter(r=>r.status==="pending").reduce((a,r)=>a+Number(r.amount||0),0))}/><Stat label="Paid" value={money(rows.filter(r=>r.status==="paid").reduce((a,r)=>a+Number(r.amount||0),0))}/></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>COD amount</th><th>Seller margin</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>#{r.orders?.external_order_id||r.order_id.slice(0,8)}</td><td>{r.orders?.customer_name||"—"}</td><td>{money(r.orders?.amount)}</td><td><b className="success-text">{money(r.amount)}</b></td><td><span className={statusClass(r.status)}>{r.status}</span></td><td>{new Date(r.created_at).toLocaleDateString("en-IN")}</td></tr>)}</tbody></table></div>{!rows.length&&<Empty title="No remittances yet" text="Delivered COD orders create the margin-remittance record automatically."/>}</section></AppShell>}

export function SellerAnalytics(){const d=useOrders("seller");const rows=d.rows;const total=rows.reduce((a,o)=>a+Number(o.amount||0),0),del=rows.filter(o=>o.status==="delivered").length,rto=rows.filter(o=>o.status==="rto").length,ndr=rows.filter(o=>o.status==="ndr"||(o.ndr_cases||[]).some(n=>n.status==="open")).length;return <AppShell role="seller" title="Analytics"><div className="analytics-head"><div><span className="section-kicker">SELLER PERFORMANCE</span><h2>Operational analytics that tell the whole story.</h2></div><span className="live-chip"><i/> Synced live</span></div><div className="stats ops-stats"><Stat label="Synced orders" value={rows.length}/><Stat label="GMV" value={money(total)}/><Stat label="Delivered" value={del}/><Stat label="NDR" value={ndr}/><Stat label="RTO" value={rto}/></div><section className="analytics-grid"><Metric title="Order funnel" values={[["Pending",rows.filter(o=>o.status==="pending").length],["Confirmed",rows.filter(o=>o.status==="confirmed").length],["Shipped",rows.filter(o=>o.status==="shipped").length],["Delivered",del],["RTO",rto]]}/><Metric title="Delivery health" values={[["Delivered",del],["NDR",ndr],["RTO",rto]]}/></section><section className="panel"><div className="panel-head"><h2>Product / order analysis</h2><span className="muted">Live from shared order data</span></div><div className="insight-grid"><div><b>{money(rows.reduce((a,o)=>a+Number(o.seller_margin||0),0))}</b><span>Total seller margin</span></div><div><b>{rows.length?Math.round(del/rows.length*100):0}%</b><span>Delivered rate</span></div><div><b>{rows.length?Math.round(rto/rows.length*100):0}%</b><span>RTO rate</span></div><div><b>{rows.length?Math.round(ndr/rows.length*100):0}%</b><span>NDR exposure</span></div></div></section></AppShell>}
function Metric({title,values}){const max=Math.max(1,...values.map(x=>x[1]));return <section className="panel metric-panel"><div className="panel-head"><h2>{title}</h2></div>{values.map(([label,v])=><div className="bar-row" key={label}><span>{label}</span><div><i style={{width:`${Math.round(v/max*100)}%`}}/></div><b>{v}</b></div>)}</section>}
function sellerOrderStats(rows){return {pending:rows.filter(o=>o.status==="pending").length,processing:rows.filter(o=>["confirmed","packed","shipped"].includes(o.status)).length,confirmed:rows.filter(o=>o.status==="confirmed").length,inTransit:rows.filter(o=>["packed","shipped","ndr"].includes(o.status)).length,delivered:rows.filter(o=>o.status==="delivered").length,ndr:rows.filter(o=>o.status==="ndr"||(o.ndr_cases||[]).some(n=>n.status==="open")).length,rto:rows.filter(o=>o.status==="rto").length,margin:rows.filter(o=>o.payment_method==="cod").reduce((a,o)=>a+Number(o.seller_margin||0),0)}; }
