import {useEffect,useMemo,useState} from "react";
import {NavLink} from "react-router-dom";
import AppShell,{Empty,Stat} from "../components/AppShell";
import {useAuth} from "../context/AuthContext";
import {supabase} from "../lib/supabase";
import {ShipmentCenter} from "./Operations";
import {MagnifyingGlassIcon,SlidersHorizontalIcon,ArchiveBoxIcon,CheckCircleIcon,PackageIcon,TrendUpIcon,ToggleLeftIcon,ToggleRightIcon,ArrowsDownUpIcon,ShoppingBagIcon,ArrowRightIcon} from "@phosphor-icons/react";
const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
function useSellerData(){const {session}=useAuth();const [data,setData]=useState({products:[],stores:[],listings:[],orders:[],shipping:[]}),[loading,setLoading]=useState(true);async function load(){if(!session?.user?.id)return;setLoading(true);const uid=session.user.id;const [{data:products},{data:stores},{data:listings},{data:orders},{data:shipping}]=await Promise.all([supabase.from("products").select("*").eq("status","active").order("created_at",{ascending:false}),supabase.from("stores").select("*").eq("seller_id",uid).order("created_at",{ascending:false}),supabase.from("listings").select("*").eq("seller_id",uid).order("created_at",{ascending:false}),supabase.from("orders").select("*").eq("seller_id",uid).order("created_at",{ascending:false}),supabase.from("shipping_configs").select("*").eq("owner_id",uid)]);setData({products:products||[],stores:stores||[],listings:listings||[],orders:orders||[],shipping:shipping||[]});setLoading(false)}useEffect(()=>{load()},[session?.user?.id]);return{data,loading,load}}
export function SellerHome(){const {data}=useSellerData();return <AppShell role="seller" title="Overview"><div className="stats"><Stat label="Marketplace products" value={data.products.length}/><Stat label="My catalog" value={data.listings.length}/><Stat label="Connected stores" value={data.stores.filter(s=>s.status==="connected").length}/><Stat label="Orders" value={data.orders.length}/></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>Available products</h2><p>Products published by vendors.</p></div><NavLink className="btn secondary" to="/seller/products">Browse all</NavLink></div><ProductMini products={data.products.slice(0,5)}/></section><section className="panel"><div className="panel-head"><div><h2>Recent orders</h2><p>Orders from your connected stores.</p></div><NavLink className="btn secondary" to="/seller/orders">View orders</NavLink></div>{data.orders.length?<OrderRows orders={data.orders.slice(0,5)}/>:<Empty title="No orders yet" text="Orders will appear here when they are created."/>}</section></div></AppShell>}
export function SellerProducts(){const {session}=useAuth();const {data,load}=useSellerData();const [search,setSearch]=useState(""),[category,setCategory]=useState("All"),[storeId,setStoreId]=useState(""),[marginType,setMarginType]=useState("fixed"),[margin,setMargin]=useState("100"),[msg,setMsg]=useState("");
const categories=useMemo(()=>["All",...Array.from(new Set(data.products.map(p=>p.category).filter(Boolean)))],[data.products]);
const filtered=useMemo(()=>data.products.filter(p=>{const text=(p.title+" "+(p.sku||"")+" "+(p.category||"")).toLowerCase();return text.includes(search.toLowerCase())&&(category==="All"||p.category===category)}),[data.products,search,category]);
async function add(p){if(!session?.user?.id)return;if(!storeId){setMsg("Connect or select a Shopify store before adding products.");return}const value=Number(margin||0);const price=marginType==="percentage"?Number(p.cost_price||0)*(1+value/100):Number(p.cost_price||0)+value;const {error}=await supabase.from("listings").upsert({product_id:p.id,seller_id:session.user.id,store_id:storeId,margin_type:marginType,margin_value:value,selling_price:Math.round(price*100)/100,status:"draft"},{onConflict:"product_id,seller_id,store_id"});setMsg(error?error.message:p.title+" added to My Catalog.");if(!error)load()}
return <AppShell role="seller" title="Products"><section className="market-banner"><div><span>BUCKET INDIA · B2B MARKETPLACE</span><h2>Find products that feel <b>ready to sell.</b></h2><p>Fresh vendor inventory, organized by category and ready for your margin.</p></div><div className="banner-badge">SELL<br/><strong>SMART</strong></div></section>
<div className="category-rail"><button className="rail-arrow" onClick={()=>window.scrollBy({left:-240,behavior:"smooth"})}>‹</button>{categories.map((cat,i)=><button key={cat} className={category===cat?"category-chip active":"category-chip"} onClick={()=>setCategory(cat)}><span>{i===0?"✦":categoryEmoji(cat)}</span><b>{cat}</b></button>)}<button className="rail-arrow" onClick={()=>window.scrollBy({left:240,behavior:"smooth"})}>›</button></div>
<div className="market-toolbar"><div className="search-box">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products, SKU or category"/></div><select value={storeId} onChange={e=>setStoreId(e.target.value)}><option value="">Select Shopify store</option>{data.stores.map(s=><option key={s.id} value={s.id}>{s.store_name||s.shop_domain}</option>)}</select><select value={marginType} onChange={e=>setMarginType(e.target.value)}><option value="fixed">₹ Fixed margin</option><option value="percentage">% Percentage margin</option></select><input className="margin-input" type="number" min="0" value={margin} onChange={e=>setMargin(e.target.value)} aria-label="Margin"/></div>
{msg&&<div className={msg.includes("added")?"alert success":"alert error"}>{msg}</div>}
<div className="market-heading"><div><span className="section-kicker">LIVE MARKETPLACE</span><h2>{category==="All"?"Trending products":category}</h2><p>{filtered.length} products from active vendors</p></div><span className="result-count">{filtered.length} results</span></div>
<div className="product-grid marketplace-grid">{filtered.map(p=><MarketplaceCard key={p.id} product={p} onAdd={()=>add(p)} marginType={marginType} margin={margin}/>)}</div>{!filtered.length&&<Empty title="No products found" text="Try another category or search term."/>}</AppShell>}
export function SellerCatalog(){
  const {session}=useAuth();
  const {data,load}=useSellerData();
  const [search,setSearch]=useState(""),[sort,setSort]=useState("newest"),[out,setOut]=useState(false),[active,setActive]=useState("all"),[store,setStore]=useState("all"),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
  const pushed=useMemo(()=>data.listings.filter(l=>!!l.shopify_product_id),[data.listings]);
  const rows=useMemo(()=>pushed.map(l=>{
    const p=data.products.find(x=>x.id===l.product_id)||{};
    const sales=data.orders.filter(o=>o.listing_id===l.id).reduce((n,o)=>n+Number(o.quantity||1),0);
    const inventory=Number(p.stock||0),vendor=Number(p.cost_price||0),sell=Number(l.selling_price||0);
    return {...l,product:p,sales,inventory,vendor,sell,margin:sell-vendor,storeName:data.stores.find(x=>x.id===l.store_id)?.store_name||"Shopify store"};
  }).filter(r=>{
    const q=search.toLowerCase().trim(),text=[r.product.title||"",r.product.sku||"",r.shopify_product_id||"",r.storeName||""].join(" ").toLowerCase(),isActive=r.status==="pushed"||r.status==="active";
    return (!q||text.includes(q))&&(!out||r.inventory<=0)&&(active==="all"||(active==="active"?isActive:!isActive))&&(store==="all"||r.store_id===store);
  }).sort((a,b)=>sort==="oldest"?new Date(a.created_at)-new Date(b.created_at):sort==="price"?b.sell-a.sell:sort==="margin"?b.margin-a.margin:new Date(b.created_at)-new Date(a.created_at)),[pushed,data.products,data.orders,data.stores,search,sort,out,active,store]);
  async function toggle(id,isActive){setBusy(id);const {error}=await supabase.from("listings").update({status:isActive?"paused":"pushed"}).eq("id",id).eq("seller_id",session.user.id);setBusy("");if(error)setMsg(error.message);else load()}
  function shopifyAdminUrl(r){if(r.shopify_product_url)return r.shopify_product_url;const st=data.stores.find(x=>x.id===r.store_id);if(!st?.shop_domain||!r.shopify_product_id)return "#";return "https://"+st.shop_domain+"/admin/products/"+r.shopify_product_id}
  return <AppShell role="seller" title="My Catalog">
    <div className="catalog-page">
      <section className="catalog-hero"><div><span className="section-kicker">SHOPIFY CATALOG</span><h2>Products you're actually selling.</h2><p>Manage products already pushed to your Shopify stores, pricing, inventory and selling status from one place.</p></div><div className="catalog-hero-stat"><ShoppingBagIcon size={20}/><b>{pushed.length}</b><span>Shopify products</span></div></section>
      <section className="panel catalog-panel">
        <div className="catalog-toolbar">
          <div className="catalog-search"><MagnifyingGlassIcon size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by product name, SKU or store"/></div>
          <div className="catalog-filter"><ArrowsDownUpIcon size={16}/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Sort by: Date added</option><option value="oldest">Sort by: Oldest first</option><option value="price">Sort by: Selling price</option><option value="margin">Sort by: Margin</option></select></div>
          <div className="catalog-filter"><SlidersHorizontalIcon size={16}/><select value={active} onChange={e=>setActive(e.target.value)}><option value="all">All status</option><option value="active">Active</option><option value="paused">Paused</option></select></div>
          <div className="catalog-filter"><ShoppingBagIcon size={16}/><select value={store} onChange={e=>setStore(e.target.value)}><option value="all">All stores</option>{data.stores.map(x=><option key={x.id} value={x.id}>{x.store_name||x.shop_domain}</option>)}</select></div>
          <button className={"catalog-toggle "+(out?"on":"")} onClick={()=>setOut(v=>!v)}>{out?<ToggleRightIcon size={22}/>:<ToggleLeftIcon size={22}/>}<span>Out of stock</span></button>
        </div>
        {msg&&<div className="alert error">{msg}</div>}
        <div className="catalog-table-meta"><span><b>{rows.length}</b> of {pushed.length} products</span><span>{out?"Showing out-of-stock products":"Inventory view enabled"}</span></div>
        {rows.length?<div className="table-wrap catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Product</th><th>Vendor price</th><th>Selling price</th><th>Margin</th><th>Inventory / Sales</th><th>Status</th><th>Active</th><th>Action</th></tr></thead><tbody>{rows.map(r=>{const isActive=r.status==="pushed"||r.status==="active";return <tr key={r.id}>
          <td><div className="catalog-product"><div className="catalog-thumb">{r.product.image_url?<img src={r.product.image_url} alt=""/>:<PackageIcon size={20}/>}</div><div><b>{r.product.title||"Product"}</b><small>{r.product.sku||"No SKU"} · {r.storeName}</small></div></div></td>
          <td><b>{money(r.vendor)}</b></td><td><b>{money(r.sell)}</b></td>
          <td><span className={"catalog-margin "+(r.margin>=0?"positive":"negative")}>{money(r.margin)}</span><small>{r.sell?Math.round(r.margin/r.sell*100):0}%</small></td>
          <td><div className="inventory-sales"><span className={r.inventory<=0?"stock-out":""}><PackageIcon size={14}/>{r.inventory<=0?"Out of stock":r.inventory+" in stock"}</span><small><TrendUpIcon size={13}/> {r.sales} sales</small></div></td>
          <td><span className={"catalog-status "+(isActive?"live":"paused")}>{isActive?"Published":"Paused"}</span>{r.inventory<=0&&<small className="catalog-status-note">Out of stock</small>}</td>
          <td><button className={"active-switch "+(isActive?"on":"")} disabled={busy===r.id} onClick={()=>toggle(r.id,isActive)} aria-label="Toggle active">{isActive?<CheckCircleIcon size={20} weight="fill"/>:<ToggleLeftIcon size={20}/>}<span>{isActive?"Active":"Paused"}</span></button></td>
          <td><a className="catalog-edit" href={shopifyAdminUrl(r)} target="_blank" rel="noreferrer"><ArrowRightIcon size={15}/><span>Edit on Shopify</span></a></td>
        </tr>})}</tbody></table></div>:<Empty title={pushed.length?"No products match these filters":"No Shopify products yet"} text={pushed.length?"Try changing your search or filters.":"Push a product from Product Marketplace and it will appear here automatically."}/>}
      </section>
    </div>
  </AppShell>
}