import {useEffect,useMemo,useState} from "react";
import {NavLink} from "react-router-dom";
import AppShell,{Empty,Stat} from "../components/AppShell";
import {useAuth} from "../context/AuthContext";
import {supabase} from "../lib/supabase";
import {ShipmentCenter} from "./Operations";
const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
function useSellerData(){const {session}=useAuth();const [data,setData]=useState({products:[],stores:[],listings:[],orders:[],shipping:[]}),[loading,setLoading]=useState(true);async function load(){if(!session?.user?.id)return;setLoading(true);const uid=session.user.id;const [{data:products},{data:stores},{data:listings},{data:orders},{data:shipping}]=await Promise.all([supabase.from("products").select("*").eq("status","active").order("created_at",{ascending:false}),supabase.from("stores").select("*").eq("seller_id",uid).order("created_at",{ascending:false}),supabase.from("listings").select("*").eq("seller_id",uid).order("created_at",{ascending:false}),supabase.from("orders").select("*").eq("seller_id",uid).order("created_at",{ascending:false}),supabase.from("shipping_configs").select("*").eq("owner_id",uid)]);setData({products:products||[],stores:stores||[],listings:listings||[],orders:orders||[],shipping:shipping||[]});setLoading(false)}useEffect(()=>{load()},[session?.user?.id]);return{data,loading,load}}
export function SellerHome(){const {data}=useSellerData();return <AppShell role="seller" title="Overview"><div className="stats"><Stat label="Marketplace products" value={data.products.length}/><Stat label="My catalog" value={data.listings.length}/><Stat label="Connected stores" value={data.stores.filter(s=>s.status==="connected").length}/><Stat label="Orders" value={data.orders.length}/></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>Available products</h2><p>Products published by vendors.</p></div><NavLink className="btn secondary" to="/seller/products">Browse all</NavLink></div><ProductMini products={data.products.slice(0,5)}/></section><section className="panel"><div className="panel-head"><div><h2>Recent orders</h2><p>Orders from your connected stores.</p></div><NavLink className="btn secondary" to="/seller/orders">View orders</NavLink></div>{data.orders.length?<OrderRows orders={data.orders.slice(0,5)}/>:<Empty title="No orders yet" text="Orders will appear here when they are created."/>}</section></div></AppShell>}
export function SellerProducts(){const {session}=useAuth();const {data,load}=useSellerData();const [search,setSearch]=useState(""),[category,setCategory]=useState("All"),[storeId,setStoreId]=useState(""),[marginType,setMarginType]=useState("fixed"),[margin,setMargin]=useState("100"),[msg,setMsg]=useState("");
const categories=useMemo(()=>["All",...Array.from(new Set(data.products.map(p=>p.category).filter(Boolean)))],[data.products]);
const filtered=useMemo(()=>data.products.filter(p=>{const text=(p.title+" "+(p.sku||"")+" "+(p.category||"")).toLowerCase();return text.includes(search.toLowerCase())&&(category==="All"||p.category===category)}),[data.products,search,category]);
async function add(p){if(!session?.user?.id)return;if(!storeId){setMsg("Connect or select a Shopify store before adding products.");return}const value=Number(margin||0);const price=marginType==="percentage"?Number(p.cost_price||0)*(1+value/100):Number(p.cost_price||0)+value;const {error}=await supabase.from("listings").upsert({product_id:p.id,seller_id:session.user.id,store_id:storeId,margin_type:marginType,margin_value:value,selling_price:Math.round(price*100)/100,status:"draft"},{onConflict:"product_id,seller_id,store_id"});setMsg(error?error.message:p.title+" added to My Catalog.");if(!error)load()}
return <AppShell role="seller" title="Products"><section className="market-banner"><div><span>BUCKET INDIA · B2B MARKETPLACE</span><h2>Find products that feel <b>ready to sell.</b></h2><p>Fresh vendor inventory, organized by category and ready for your margin.</p></div><div className="banner-badge">SELL<br/><strong>SMART</strong></div></section>
<div className="category-rail"><button className="rail-arrow" onClick={()=>window.scrollBy({left:-240,behavior:"smooth"})}>‹</button>{categories.map((cat,i)=><button key={cat} className={category===cat?"category-chip active":"category-chip"} onClick={()=>setCategory(cat)}><span>{i===0?"✦":categoryEmoji(cat)}</span><b>{cat}</b></button>)}<button className="rail-arrow" onClick={()=>window.scrollBy({left:240,behavior:"smooth"})}>›</button></div>
<div className="market-toolbar"><div className="search-box">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products, SKU or category"/></div><select value={storeId} onChange={e=>setStoreId(e.target.value)}><option value="">Select Shopify store</option>{data.stores.map(s=><option key={s.id} value={s.id}>{s.store_name||s.shop_domain}</option>)}</select><select value={marginType} onChange={e=>setMarginType(e.target.value)}><option value="fixed">₹ Fixed margin</option><option value="percentage">% Percentage margin</option></select><input className="margin-input" type="number" min="0" value={margin} onChange={e=>setMargin(e.target.value)} aria-label="Margin"/></div>
{msg&&<div className={msg.includes("added")?"alert success":"alert error"}>{msg}</div>}
<div className="market-heading"><div><span className="section-kicker">LIVE MARKETPLACE</span><h2>{category==="All"?"Trending products":category}</h2><p>{filtered.length} products from active vendors</p></div><span className="result-count">{filtered.length} results</span></div>
<div className="product-grid marketplace-grid">{filtered.map(p=><MarketplaceCard key={p.id} product={p} onAdd={()=>add(p)} marginType={marginType} margin={margin}/>)}</div>{!filtered.length&&<Empty title="No products found" text="Try another category or search term."/>}</AppShell>}
export function SellerCatalog(){const {data,load}=useSellerData();async function update(id,status){const {error}=await supabase.from("listings").update({status}).eq("id",id);if(!error)load()}return <AppShell role="seller" title="My Catalog"><section className="panel"><div className="panel-head"><div><h2>Catalog listings</h2><p>Products you have selected and priced.</p></div></div>{data.listings.length?<div className="table-wrap"><table><thead><tr><th>Product</th><th>Store</th><th>Margin</th><th>Selling price</th><th>Status</th><th/></tr></thead><tbody>{data.listings.map(l=><tr key={l.id}><td>{data.products.find(p=>p.id===l.product_id)?.title||"Product"}</td><td>{data.stores.find(s=>s.id===l.store_id)?.store_name||"—"}</td><td>{l.margin_type==="percentage"?`${l.margin_value}%`:money(l.margin_value)}</td><td>{money(l.selling_price)}</td><td><span className="badge">{l.status}</span></td><td><select value={l.status} onChange={e=>update(l.id,e.target.value)}><option value="draft">draft</option><option value="pushed">pushed</option><option value="paused">paused</option><option value="error">error</option></select></td></tr>)}</tbody></table></div>:<Empty title="Your catalog is empty" text="Browse marketplace products and add them here."/ >}</section></AppShell>}
export function SellerStores(){const {session}=useAuth();const {data,load}=useSellerData();const [form,setForm]=useState({name:"",domain:""}),[msg,setMsg]=useState("");async function add(e){e.preventDefault();const domain=form.domain.trim().replace(/^https?:\/\//,"").replace(/\/$/,"");const {error}=await supabase.from("stores").insert({seller_id:session.user.id,platform:"shopify",store_name:form.name.trim()||domain,shop_domain:domain,status:"connected"});setMsg(error?error.message:"Store connected.");if(!error){setForm({name:"",domain:""});load()}}async function remove(id){const {error}=await supabase.from("stores").delete().eq("id",id);setMsg(error?error.message:"Store removed.");if(!error)load()}return <AppShell role="seller" title="Stores"><div className="two-col"><form className="panel form-stack" onSubmit={add}><h2>Connect Shopify store</h2><p className="muted">Store identity is stored in Supabase. Live OAuth/token sync belongs server-side.</p><label>Store name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="My Store"/></label><label>Shop domain<input value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})} placeholder="my-store.myshopify.com" required/></label><button className="btn primary">Connect store</button>{msg&&<div className="alert success">{msg}</div>}</form><section className="panel"><h2>Your stores</h2>{data.stores.length?data.stores.map(s=><div className="list-item" key={s.id}><div><b>{s.store_name}</b><span>{s.shop_domain}</span></div><span className="badge">{s.status}</span><button className="btn danger" onClick={()=>remove(s.id)}>Remove</button></div>):<Empty title="No stores connected" text="Connect a Shopify store to start building your catalog."/ >}</section></div></AppShell>}
export function SellerOrders(){const {data}=useSellerData();return <AppShell role="seller" title="Orders"><section className="panel"><div className="panel-head"><div><h2>Seller orders</h2><p>Track order status and fulfillment.</p></div></div>{data.orders.length?<OrderRows orders={data.orders}/>:<Empty title="No orders" text="Your Shopify orders will appear here once order sync is connected."/ >}</section></AppShell>}
export function SellerShipping(){return <ShipmentCenter role="seller"/>;}function categoryEmoji(c){const x=c.toLowerCase();if(x.includes("home")||x.includes("kitchen"))return "⌂";if(x.includes("pet"))return "◉";if(x.includes("fitness")||x.includes("well"))return "✦";if(x.includes("men")||x.includes("women"))return "◌";if(x.includes("garden"))return "♧";if(x.includes("access"))return "◈";return "◍"}
function MarketplaceCard({product,onAdd,marginType,margin}){const base=Number(product.cost_price||0),value=Number(margin||0),sell=marginType==="percentage"?base*(1+value/100):base+value;const old=Math.max(base*1.25,sell*1.12);return <article className="market-product-card"><div className="market-image">{product.image_url?<img src={product.image_url} alt={product.title}/>:<div className="image-placeholder">{product.title?.slice(0,1)||"B"}</div>}<button className="heart" aria-label="Save product">♡</button><span className="market-tag">{product.category||"Trending"}</span></div><div className="market-body"><div className="market-price"><del>{money(old)}</del><strong>{money(sell)}</strong><span>{Math.max(1,Math.round((old-sell)/Math.max(old,1)*100))}% OFF</span></div><h3 title={product.title}>{product.title}</h3><div className="market-meta"><span>◉ {product.stock>1000?"1K+":product.stock||0} in stock</span><span>◇ {product.sku||"Vendor SKU"}</span></div><div className="market-card-actions"><button className="btn primary" onClick={onAdd}>Add to catalog</button><span className="margin-preview">+{marginType==="percentage"?value+"%":money(value)} margin</span></div></div></article>}

export function SellerFeature({title,eyebrow="SELLER TOOL",description="This workspace is ready for the next stage of your selling workflow."}){return <AppShell role="seller" title={title}><section className="seller-feature-page"><span className="section-kicker">{eyebrow}</span><h2>{title}</h2><p>{description}</p><div className="feature-grid"><div className="feature-card"><span>01</span><div><b>Connected to your marketplace</b><p>Vendor products, catalog selections and seller activity stay in the same Supabase workspace.</p></div><strong>✓</strong></div><div className="feature-card"><span>02</span><div><b>Ready for live integrations</b><p>Use this surface for analytics, shipping, ads, RTO or operational automation.</p></div><strong>→</strong></div><div className="feature-card"><span>03</span><div><b>Action center</b><p>Build the next workflow here without changing the seller navigation.</p></div><strong>+</strong></div></div></section></AppShell>}
