import {useEffect,useMemo,useState} from "react";
import {useAuth} from "../context/AuthContext";
import {supabase} from "../lib/supabase";
import AppShell,{Empty} from "../components/AppShell";
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2});
const CATS=["All","Kitchen","Home","Bike & Car","Trending","Under ₹100","Religious","Men","Women","Fitness"];
const emoji=c=>({Kitchen:"⌁",Home:"⌂","Bike & Car":"◈",Trending:"✦","Under ₹100":"₹",Religious:"☼",Men:"◌",Women:"◌",Fitness:"✧",All:"✦"}[c]||"◍");
function useMarketplace(){
 const {session}=useAuth();const [products,setProducts]=useState([]),[stores,setStores]=useState([]),[loading,setLoading]=useState(true);
 async function load(){if(!session?.user?.id)return;setLoading(true);const uid=session.user.id;const [{data:p},{data:s}]=await Promise.all([supabase.from("products").select("*").eq("status","active").order("created_at",{ascending:false}),supabase.from("stores").select("*").eq("seller_id",uid).order("created_at",{ascending:false})]);setProducts(p||[]);setStores(s||[]);setLoading(false)}
 useEffect(()=>{load()},[session?.user?.id]);return{products,stores,loading,load};
}
export default function SellerMarketplace(){
 const {session}=useAuth();const {products,stores,loading,load}=useMarketplace();const [search,setSearch]=useState(""),[category,setCategory]=useState("All"),[selected,setSelected]=useState(null),[pushProduct,setPushProduct]=useState(null),[price,setPrice]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const connected=stores.find(s=>s.status==="connected");
 const filtered=useMemo(()=>products.filter(p=>{const hay=(p.title+" "+(p.sku||"")+" "+(p.category||"")).toLowerCase(),cat=(p.category||"").toLowerCase();return hay.includes(search.toLowerCase())&&(category==="All"||(category==="Under ₹100"&&Number(p.cost_price||0)<100)||cat.includes(category.toLowerCase()))}),[products,search,category]);
 function startPush(p){if(!connected){setMsg("Add your Shopify store to push this product.");return}setSelected(null);setPushProduct(p);setPrice(String(Math.ceil(Number(p.cost_price||0)+Number(p.rto_charge??70))));setMsg("")}
 async function publish(){if(!session?.user?.id||!pushProduct||!connected)return;const selling=Number(price),cost=Number(pushProduct.cost_price||0);if(!Number.isFinite(selling)||selling<=0){setMsg("Enter a valid selling price.");return}setBusy(true);setMsg("");const {data:listing,error}=await supabase.from("listings").upsert({product_id:pushProduct.id,seller_id:session.user.id,store_id:connected.id,margin_type:"fixed",margin_value:selling-cost,selling_price:selling,status:"draft"},{onConflict:"product_id,seller_id,store_id"}).select("id").single();if(error){setBusy(false);setMsg(error.message);return}const {data:res,error:fnError}=await supabase.functions.invoke("shopify-push-product",{body:{listing_id:listing.id}});setBusy(false);if(fnError||res?.error){setMsg(fnError?.message||res?.error||"Could not push product to Shopify.");return}setPushProduct(null);setMsg("Product pushed to Shopify successfully.");load()}
 if(loading)return <AppShell role="seller" title="Product Marketplace"><div className="loading"><div className="spinner"/></div></AppShell>;
 return <AppShell role="seller" title="Product Marketplace"><section className="market-banner marketplace-hero-v2"><div><span>BUCKET INDIA · SELLER MARKETPLACE</span><h2>Products built to be <b>sold.</b></h2><p>Discover vendor products, review the economics, then launch directly to your Shopify store.</p></div><div className="banner-badge">READY<br/><strong>TO SELL</strong></div></section>
 <div className="category-rail fixed-category-rail">{CATS.map(c=><button key={c} className={category===c?"category-chip active":"category-chip"} onClick={()=>setCategory(c)}><span>{emoji(c)}</span><b>{c}</b></button>)}</div>
 <div className="market-toolbar marketplace-toolbar-v2"><div className="search-box">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products, SKU or category"/></div><span className="marketplace-filter-note">{filtered.length} products · vendor catalog</span></div>
 {msg&&<div className={msg.toLowerCase().includes("successfully")?"alert success":"alert error"}>{msg}</div>}
 <div className="market-heading"><div><span className="section-kicker">LIVE VENDOR CATALOG</span><h2>{category==="All"?"Explore products":category}</h2><p>Open any product for full details and Shopify publishing.</p></div><span className="result-count">{filtered.length} results</span></div>
 <div className="product-grid marketplace-grid">{filtered.map(p=><MarketplaceCard key={p.id} product={p} onOpen={()=>setSelected(p)} onPush={()=>startPush(p)}/>)}</div>{!filtered.length&&<Empty title="No products found" text="Try another category or search phrase."/>}
 {selected&&<ProductDetail product={selected} onClose={()=>setSelected(null)} onPush={()=>startPush(selected)}/>}
 {pushProduct&&<PushDrawer product={pushProduct} price={price} setPrice={setPrice} onClose={()=>setPushProduct(null)} onConfirm={publish} busy={busy}/>}
 </AppShell>
}
function MarketplaceCard({product,onOpen,onPush}){const cost=Number(product.cost_price||0);return <article className="market-product-card marketplace-card-v2" onClick={onOpen}><div className="market-image">{product.image_url?<img src={product.image_url} alt={product.title}/>:<div className="image-placeholder">{product.title?.slice(0,1)||"B"}</div>}<span className="market-tag">{product.category||"Trending"}</span><span className="vendor-live-dot">VENDOR LIVE</span></div><div className="market-body"><div className="market-price"><strong>{money(cost)}</strong><span>vendor cost</span></div><h3 title={product.title}>{product.title}</h3><p className="market-desc">{product.description||"Marketplace-ready product from a Bucket India vendor."}</p><div className="market-meta"><span>◉ {product.stock>1000?"1K+":product.stock||0} stock</span><span>◇ {product.sku||"Vendor SKU"}</span></div><div className="market-card-actions"><button className="btn secondary" onClick={e=>{e.stopPropagation();onOpen()}}>View details</button><button className="btn primary" onClick={e=>{e.stopPropagation();onPush()}}>Push to Shopify</button></div></div></article>}
function ProductDetail({product,onClose,onPush}){const cost=Number(product.cost_price||0),rto=Number(product.rto_charge??70);return <div className="market-overlay" onMouseDown={onClose}><section className="product-detail-modal" onMouseDown={e=>e.stopPropagation()}><button className="detail-close" onClick={onClose}>×</button><div className="detail-media">{product.image_url?<img src={product.image_url} alt={product.title}/>:<div className="detail-placeholder">{product.title?.slice(0,1)||"B"}</div>}</div><div className="detail-copy"><span className="badge">{product.category||"Trending"}</span><h2>{product.title}</h2><div className="detail-price">{money(cost)} <small>vendor cost</small></div><p>{product.description||"A marketplace-ready product supplied by a Bucket India vendor."}</p><div className="detail-facts"><span><b>Vendor cost</b>{money(cost)}</span><span><b>Stock</b>{product.stock>1000?"1K+":product.stock||0}</span><span><b>SKU</b>{product.sku||"Vendor SKU"}</span><span><b>RTO charge</b>{money(rto)}</span></div><div className="detail-note"><b>Seller economics</b><span>Choose your own selling price. The vendor-defined RTO charge is displayed before publishing.</span></div><button className="btn primary detail-push" onClick={onPush}>Push to Shopify <span>→</span></button></div></section></div>}
function PushDrawer({product,price,setPrice,onClose,onConfirm,busy}){const cost=Number(product.cost_price||0),rto=Number(product.rto_charge??70),p=Number(price||0),gross=p-cost,after=gross-rto;return <div className="market-overlay drawer-overlay" onMouseDown={onClose}><aside className="push-drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="section-kicker">SHOPIFY PUBLISH</span><h2>Set your selling price</h2><p>Your price drives the seller margin.</p></div><button className="detail-close" onClick={onClose}>×</button></div><div className="drawer-product"><div>{product.image_url?<img src={product.image_url} alt=""/>:<span>{product.title?.slice(0,1)||"B"}</span>}</div><section><b>{product.title}</b><small>Vendor cost · {money(cost)}</small></section></div><label className="price-editor">Selling price<input type="number" min="1" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><div className="economics-card"><div><span>Vendor cost</span><b>{money(cost)}</b></div><div><span>Your gross margin</span><b className={gross>=0?"positive":"negative"}>{money(gross)}</b></div><div><span>RTO charge / reserve</span><b>{money(rto)}</b></div><div className="economics-total"><span>Estimated margin after RTO</span><b className={after>=0?"positive":"negative"}>{money(after)}</b></div></div><div className="terms-box"><b>Before you publish</b><p>RTO charges are vendor-defined. Shipping, COD/payment fees, taxes and other store costs can change final profit.</p><label><input type="checkbox" defaultChecked/> I understand the displayed economics.</label></div><button className="btn primary full publish-btn" disabled={busy||p<=0} onClick={onConfirm}>{busy?"Publishing to Shopify…":"Confirm & Push to Shopify →"}</button></aside></div>}
