import {useEffect,useMemo,useState} from "react";
import {NavLink} from "react-router-dom";
import AppShell,{Empty,Stat} from "../components/AppShell";
import {useAuth} from "../context/AuthContext";
import {supabase} from "../lib/supabase";
import {ChartLineUp,Package,ShoppingCart,Truck,WarningCircle,Wallet,Storefront,Gear,CheckCircle,ArrowRight,ArrowUpRight,Plus,UploadSimple,Funnel,CalendarBlank,CurrencyInr,ShieldCheck,Key,PlugsConnected,MapPin,Receipt,UsersThree,Clock,Check,Lightning} from "@phosphor-icons/react";

const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
const statuses=["pending","confirmed","packed","shipped","delivered","ndr","rto","cancelled"];
const providers=[
 {id:"shiprocket",name:"Shiprocket",tag:"Multi-courier",icon:"S",desc:"Multi-carrier shipping, labels and tracking."},
 {id:"delhivery",name:"Delhivery",tag:"National",icon:"D",desc:"Pan-India parcel delivery and tracking."},
 {id:"bluedart",name:"Blue Dart",tag:"Express",icon:"B",desc:"Express parcel and priority delivery."},
 {id:"ekart",name:"EKart",tag:"Commerce",icon:"E",desc:"Integrated logistics for ecommerce orders."},
 {id:"xpressbees",name:"Xpressbees",tag:"Growth",icon:"X",desc:"Domestic parcel and ecommerce logistics."},
 {id:"manual",name:"Manual / Own Courier",tag:"Flexible",icon:"M",desc:"Operate your own courier workflow."}
];

function Card({children,className=""}){return <section className={"panel "+className}>{children}</section>}
function Head({kicker,title,text,action}){return <div className="panel-head"><div>{kicker&&<span className="section-kicker">{kicker}</span>}<h2>{title}</h2>{text&&<p>{text}</p>}</div>{action}</div>}

function useVendorData(){
 const {session}=useAuth(); const [vendor,setVendor]=useState(null),[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[shipping,setShipping]=useState([]),[loading,setLoading]=useState(true);
 const load=async()=>{
  if(!session?.user?.id)return; setLoading(true);
  const {data:v}=await supabase.from("vendors").select("*").eq("owner_id",session.user.id).maybeSingle();
  if(!v){setVendor(null);setProducts([]);setOrders([]);setShipping([]);setLoading(false);return}
  const [{data:p},{data:o},{data:s}]=await Promise.all([
   supabase.from("products").select("*").eq("vendor_id",v.id).order("created_at",{ascending:false}),
   supabase.from("orders").select("*").eq("vendor_id",v.id).order("created_at",{ascending:false}),
   supabase.from("vendor_shipping_connections").select("id,provider,connection_mode,enabled,account_label,api_key_last4,secret_last4,created_at,updated_at").eq("vendor_id",v.id).order("created_at",{ascending:false})
  ]);
  setVendor(v);setProducts(p||[]);setOrders(o||[]);setShipping(s||[]);setLoading(false);
 };
 useEffect(()=>{load()},[session?.user?.id]);
 return {vendor,products,orders,shipping,loading,load,userId:session?.user?.id};
}

export function VendorHome(){
 const d=useVendorData(); const revenue=d.orders.reduce((a,o)=>a+Number(o.amount||0),0);
 const delivered=d.orders.filter(o=>o.status==="delivered").length,exceptions=d.orders.filter(o=>["ndr","rto"].includes(o.status)).length;
 const active=d.products.filter(p=>p.status==="active").length,low=d.products.filter(p=>Number(p.stock||0)<10).length;
 const delivery=d.orders.length?Math.round(delivered/d.orders.length*100):0;
 const health=Math.max(42,Math.min(98,60+Math.min(20,active*2)+Math.min(12,delivery/5)-Math.min(15,low*2)-Math.min(15,exceptions*2)));
 return <AppShell role="vendor" title="Overview">
  <section className="vendor-os-hero"><div><span className="hero-kicker">BUCKET INDIA · VENDOR OS</span><h2>Your supply business, <span>fully connected.</span></h2><p>Publish products, keep inventory healthy, confirm seller demand and move every order through fulfillment from one operating cockpit.</p><div className="hero-actions"><NavLink className="btn primary" to="/vendor/products"><Plus size={16}/> Add product</NavLink><NavLink className="btn glass" to="/vendor/import"><UploadSimple size={16}/> Bulk import</NavLink></div></div><div className="vendor-health-hero"><span>SUPPLY HEALTH</span><b>{Math.round(health)}</b><small>/100</small><i style={{width:health+"%"}}/></div></section>
  <div className="stats modern-stats"><Stat label="Catalog products" value={d.products.length}/><Stat label="Live products" value={active} hint="Visible to sellers"/><Stat label="Order value" value={money(revenue)}/><Stat label="Delivery rate" value={delivery+"%"}/><Stat label="Low stock" value={low} hint="Below 10 units"/><Stat label="Exceptions" value={exceptions} hint="NDR + RTO"/></div>
  <div className="vendor-home-grid">
   <Card><Head kicker="FULFILLMENT PIPELINE" title="Orders moving through your network" text="Vendor status changes flow into the seller shipping journey."/><div className="vendor-pipeline">{["pending","confirmed","packed","shipped","delivered"].map(s=><NavLink to="/vendor/orders" key={s}><b>{d.orders.filter(o=>o.status===s).length}</b><span>{s.replace("_"," ")}</span><i/></NavLink>)}</div><NavLink className="btn secondary" to="/vendor/orders">Open fulfillment queue <ArrowRight size={14}/></NavLink></Card>
   <Card><Head kicker="ATTENTION" title="Keep supply moving"/><div className="vendor-attention-list"><NavLink to="/vendor/inventory"><span><Package/></span><div><b>{low?low+" products need stock":"Inventory is healthy"}</b><small>{low?"Review low-stock SKUs before seller demand grows.":"Keep stock levels updated for accurate seller availability."}</small></div><ArrowRight/></NavLink><NavLink to="/vendor/exceptions"><span><WarningCircle/></span><div><b>{exceptions?exceptions+" delivery exceptions":"No active exceptions"}</b><small>{exceptions?"Review NDR/RTO events and next actions.":"Your delivery exception queue is clear."}</small></div><ArrowRight/></NavLink><NavLink to="/vendor/shipping"><span><Truck/></span><div><b>{d.shipping.length?d.shipping.length+" shipping connection(s)":"Connect shipping"}</b><small>{d.shipping.length?"Your fulfillment network is configured.":"Choose a provider or configure API credentials."}</small></div><ArrowRight/></NavLink></div></Card>
  </div>
  <Card><Head kicker="CATALOG AT SCALE" title="Operate your product network" text="The vendor panel is built around the actions that directly affect seller success."/><div className="vendor-action-grid">
   {[["Add product","Create a marketplace-ready SKU with RTO economics.","/vendor/products",Package],["Bulk import","Upload a CSV with hundreds of products.","/vendor/import",UploadSimple],["Inventory","Monitor stock and prevent seller-side overselling.","/vendor/inventory",Package],["Shipping partners","Connect a courier from the provider pool or API.","/vendor/shipping",Truck],["Analytics","Track GMV, delivery, RTO and product movement.","/vendor/analytics",ChartLineUp],["Settings","KYC, billing, bank, account and alerts.","/vendor/settings",Gear]].map(([t,x,h,I])=><NavLink className="vendor-action-card" to={h} key={t}><span><I size={20}/></span><div><b>{t}</b><p>{x}</p></div><ArrowUpRight size={15}/></NavLink>)}
  </div></Card>
  <Card><Head kicker="LATEST ORDER FLOW" title="Recent seller demand" action={<NavLink className="btn compact secondary" to="/vendor/orders">View all</NavLink>}/>{d.orders.length?<div className="vendor-order-list">{d.orders.slice(0,6).map(o=><NavLink to="/vendor/orders" className="vendor-order-row" key={o.id}><div><b>#{o.external_order_id||o.id.slice(0,8)}</b><span>{o.customer_name||"Customer"} · Qty {o.quantity||1}</span></div><strong>{money(o.amount)}</strong><span className={"status-pill "+o.status}>{o.status}</span><ArrowRight size={14}/></NavLink>)}</div>:<Empty title="No seller orders yet" text="Confirmed seller orders will appear here when demand reaches your catalog."/ >}</Card>
 </AppShell>
}

export function VendorProducts(){
 const d=useVendorData(); const blank={title:"",sku:"",description:"",category:"",cost_price:"",rto_charge:"70",stock:"0",image_url:"",status:"active"};
 const [editing,setEditing]=useState(null),[form,setForm]=useState(blank),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 function edit(p){setEditing(p.id);setForm({...blank,...p,cost_price:p.cost_price??"",rto_charge:p.rto_charge??70,stock:p.stock??0})}
 async function save(e){e.preventDefault();if(!d.vendor)return setMsg("Vendor profile is not ready.");if(!form.title.trim())return setMsg("Product title is required.");setBusy(true);
  const payload={vendor_id:d.vendor.id,title:form.title.trim(),sku:form.sku.trim()||null,description:form.description.trim()||null,category:form.category.trim()||"General",cost_price:Math.max(0,Number(form.cost_price||0)),rto_charge:Math.max(0,Number(form.rto_charge||0)),stock:Math.max(0,Number(form.stock||0)),image_url:form.image_url.trim()||null,status:form.status,updated_at:new Date().toISOString()};
  const q=editing?supabase.from("products").update(payload).eq("id",editing):supabase.from("products").insert(payload);const {error}=await q;setBusy(false);setMsg(error?error.message:editing?"Product updated.":"Product published to the seller marketplace.");if(!error){setEditing(null);setForm(blank);d.load()}}
 async function remove(id){if(!confirm("Delete this product?"))return;const {error}=await supabase.from("products").delete().eq("id",id);setMsg(error?error.message:"Product deleted.");if(!error)d.load()}
 return <AppShell role="vendor" title="Products">
  <section className="vendor-module-hero"><div><span className="section-kicker">VENDOR CATALOG</span><h2>Products that sellers can <span>launch profitably.</span></h2><p>Set the real vendor economics — including RTO charge — before a product reaches the marketplace.</p></div><div className="hero-metric"><b>{d.products.length}</b><span>catalog SKUs</span></div></section>
  <div className="vendor-product-workspace"><form className="panel vendor-product-form" onSubmit={save}><Head kicker={editing?"EDIT SKU":"CREATE SKU"} title={editing?"Update product":"Add a product"} text="Everything sellers need to understand the product and its economics."/><label>Product title<input value={form.title} onChange={e=>set("title",e.target.value)} placeholder="Portable USB Mini Blender" required/></label><div className="form-row"><label>SKU<input value={form.sku} onChange={e=>set("sku",e.target.value)} placeholder="BI-1001"/></label><label>Category<input value={form.category} onChange={e=>set("category",e.target.value)} placeholder="Kitchen & Household"/></label></div><div className="vendor-economics-callout"><div><span>VENDOR ECONOMICS</span><b>Protect the margin before publishing.</b></div><ShieldCheck size={21}/></div><div className="form-row"><label>Vendor cost<input type="number" min="0" value={form.cost_price} onChange={e=>set("cost_price",e.target.value)} placeholder="499" required/><small>Your supply cost per unit.</small></label><label>RTO charge<input type="number" min="0" value={form.rto_charge} onChange={e=>set("rto_charge",e.target.value)} placeholder="70"/><small>Charge/reserve sellers see in product economics.</small></label></div><div className="form-row"><label>Available stock<input type="number" min="0" value={form.stock} onChange={e=>set("stock",e.target.value)}/></label><label>Status<select value={form.status} onChange={e=>set("status",e.target.value)}><option value="active">Active — visible</option><option value="inactive">Inactive — hidden</option><option value="out_of_stock">Out of stock</option></select></label></div><label>Product image URL<input value={form.image_url} onChange={e=>set("image_url",e.target.value)} placeholder="https://..."/></label><label>Description<textarea rows="4" value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Short seller-facing product description"/></label><div className="vendor-form-actions"><button className="btn primary" disabled={busy}>{busy?"Saving…":editing?"Save product":"Publish to marketplace"} <ArrowRight size={14}/></button>{editing&&<button type="button" className="btn secondary" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</div>{msg&&<div className={"alert "+(msg.includes("required")||msg.includes("ready")||msg.includes("failed")?"error":"success")}>{msg}</div>}</form>
  <Card className="vendor-economics-preview"><Head kicker="LIVE SELLER VIEW" title="Marketplace economics" text="A quick view of what the seller needs to price around."/><div className="vendor-preview-number"><span>Vendor cost</span><b>{money(form.cost_price)}</b></div><div className="vendor-preview-number"><span>RTO charge / reserve</span><b>{money(form.rto_charge)}</b></div><div className="vendor-preview-number"><span>Cost + RTO exposure</span><strong>{money(Number(form.cost_price||0)+Number(form.rto_charge||0))}</strong></div><div className="vendor-preview-note"><CheckCircle size={16}/> Sellers can model this product before pushing it to Shopify.</div></Card></div>
  <Card className="vendor-catalog-list"><Head kicker="CATALOG" title="Your product network" text={d.products.length+" products · "+d.products.filter(p=>p.status==="active").length+" live"}/>{d.products.length?<div className="vendor-product-table"><div className="vendor-table-head"><span>Product</span><span>Economics</span><span>Stock</span><span>Status</span><span>Action</span></div>{d.products.map(p=><article key={p.id}><div className="vendor-product-cell"><span>{p.image_url?<img src={p.image_url} alt=""/>:<Package size={19}/>}</span><div><b>{p.title}</b><small>{p.sku||"No SKU"} · {p.category||"General"}</small></div></div><div><b>{money(p.cost_price)}</b><small>RTO {money(p.rto_charge)}</small></div><div><b>{p.stock||0}</b><small>{Number(p.stock||0)<10?"Low stock":"Healthy"}</small></div><span className={"status-pill "+(p.status||"inactive")}>{p.status}</span><div className="actions"><button className="btn compact secondary" onClick={()=>edit(p)}>Edit</button><button className="btn compact danger" onClick={()=>remove(p.id)}>Delete</button></div></article>)}</div>:<Empty title="No products yet" text="Create your first SKU or bulk import your catalog."/ >}</Card>
 </AppShell>
}

export function VendorOrders(){
 const d=useVendorData(); const [selected,setSelected]=useState(null),[tab,setTab]=useState("all"),[search,setSearch]=useState(""),[busy,setBusy]=useState("");
 const rows=useMemo(()=>d.orders.filter(o=>(tab==="all"||o.status===tab)&&(!search||[o.external_order_id,o.customer_name,o.customer_phone,o.awb].join(" ").toLowerCase().includes(search.toLowerCase()))),[d.orders,tab,search]);
 async function update(o,status){setBusy(o.id);const patch={status,updated_at:new Date().toISOString(),last_event_at:new Date().toISOString()};if(status==="confirmed")patch.confirmed_at=new Date().toISOString();if(status==="packed")patch.packed_at=new Date().toISOString();if(status==="shipped")patch.shipped_at=new Date().toISOString();if(status==="delivered")patch.delivered_at=new Date().toISOString();if(status==="rto")patch.rto_at=new Date().toISOString();const {error}=await supabase.from("orders").update(patch).eq("id",o.id);setBusy("");if(error)alert(error.message);else d.load()}
 return <AppShell role="vendor" title="Orders">
  <section className="vendor-module-hero compact"><div><span className="section-kicker">ORDER CONTROL</span><h2>Confirm, pack and ship <span>seller demand.</span></h2><p>Every vendor status feeds the same shipping journey visible to the seller.</p></div><div className="hero-metric"><b>{rows.length}</b><span>matching orders</span></div></section>
  <Card><div className="vendor-order-toolbar"><div className="orders-search"><Funnel size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search order, customer, mobile or AWB"/></div><div className="vendor-tabs">{["all","pending","confirmed","packed","shipped","delivered","ndr","rto"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x==="all"?"All":x}</button>)}</div></div>{rows.length?<div className="vendor-orders-table"><div className="vendor-orders-head"><span>Order</span><span>Customer</span><span>Value</span><span>Journey</span><span>Action</span></div>{rows.map(o=><article key={o.id}><div><b>#{o.external_order_id||o.id.slice(0,8)}</b><small>{new Date(o.created_at).toLocaleDateString("en-IN")} · {o.payment_method||"COD"}</small></div><div><b>{o.customer_name||"Customer"}</b><small>{o.customer_phone||"—"}</small></div><strong>{money(o.amount)}</strong><div className="vendor-order-journey"><span className={"done "+(["confirmed","packed","shipped","delivered","ndr","rto"].includes(o.status)?"":"current")}>Confirmed</span><span className={["packed","shipped","delivered"].includes(o.status)?"done":""}>Packed</span><span className={["shipped","delivered"].includes(o.status)?"done":""}>Shipped</span><span className={o.status==="delivered"?"done":""}>{o.status==="ndr"?"NDR":o.status==="rto"?"RTO":"Delivered"}</span></div><div className="actions"><button className="btn compact secondary" onClick={()=>setSelected(o)}>View</button>{o.status==="pending"&&<button className="btn compact primary" disabled={busy===o.id} onClick={()=>update(o,"confirmed")}>{busy===o.id?"…":"Confirm"}</button>}{["confirmed","packed"].includes(o.status)&&<button className="btn compact primary" disabled={busy===o.id} onClick={()=>update(o,o.status==="confirmed"?"packed":"shipped")}>{o.status==="confirmed"?"Pack":"Ship"}</button>}</div></article>)}</div>:<Empty title="No matching orders" text="Seller demand will appear here when orders are confirmed."/ >}</Card>
  {selected&&<OrderDrawer order={selected} onClose={()=>setSelected(null)} onUpdate={s=>{update(selected,s);setSelected(null)}}/>}
 </AppShell>
}

function OrderDrawer({order,onClose,onUpdate}){const steps=[["Order received","pending","Seller order entered the network."],["Confirmed","confirmed","Vendor accepted the order for fulfillment."],["Packed","packed","Product prepared and handed to shipping."],["Shipped","shipped","Courier pickup and transit started."],["Delivered","delivered","Customer received the parcel."]];const idx=Math.max(0,steps.findIndex(x=>x[1]===order.status));return <div className="vendor-drawer-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="vendor-order-drawer"><div className="drawer-head"><div><span className="section-kicker">ORDER JOURNEY</span><h2>#{order.external_order_id||order.id.slice(0,8)}</h2><p>{order.customer_name||"Customer"} · {order.customer_phone||"No phone"}</p></div><button onClick={onClose}>×</button></div><div className="vendor-order-summary"><b>{money(order.amount)}</b><span>{order.quantity||1} unit · {order.payment_method||"COD"}</span><span>{order.awb?"AWB "+order.awb:"AWB pending"}</span></div><div className="vendor-timeline">{steps.map((s,i)=><div className={i<=idx?"active":""} key={s[0]}><i>{i<idx?<Check size={13}/>:i===idx?<Clock size={13}/>:<span/>}</i><div><b>{s[0]}</b><small>{s[2]}</small></div></div>)}</div><div className="vendor-order-actions"><b>Update fulfillment</b><div>{order.status==="pending"&&<button className="btn primary" onClick={()=>onUpdate("confirmed")}>Confirm order</button>}{order.status==="confirmed"&&<button className="btn primary" onClick={()=>onUpdate("packed")}>Mark packed</button>}{order.status==="packed"&&<button className="btn primary" onClick={()=>onUpdate("shipped")}>Mark shipped</button>}{order.status==="shipped"&&<button className="btn primary" onClick={()=>onUpdate("delivered")}>Mark delivered</button>}</div></div></aside></div>}

export function VendorShipping(){
 const d=useVendorData(); const [mode,setMode]=useState("pool"),[provider,setProvider]=useState("shiprocket"),[apiKey,setApiKey]=useState(""),[secret,setSecret]=useState(""),[label,setLabel]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const active=d.shipping.find(x=>x.provider===provider);
 async function connect(){if(!d.vendor)return;setBusy(true);const payload={vendor_id:d.vendor.id,provider,connection_mode:mode,enabled:true,account_label:label.trim()||provider,api_key_last4:mode==="api"&&apiKey?apiKey.slice(-4):active?.api_key_last4||null,secret_last4:mode==="api"&&secret?secret.slice(-4):active?.secret_last4||null,config:{mode,configured:mode==="pool"||!!apiKey,credential_hint:mode==="api"?"API credentials captured; provider execution should be handled server-side.":"Provider pool connection"}};const {error}=await supabase.from("vendor_shipping_connections").upsert(payload,{onConflict:"vendor_id,provider"});setBusy(false);setMsg(error?error.message:"Shipping partner connection saved.");if(!error){setApiKey("");setSecret("");d.load()}}
 return <AppShell role="vendor" title="Shipping Partners">
  <section className="shipping-connect-hero"><div><span className="hero-kicker">SHIPPING NETWORK</span><h2>Connect the carriers that <span>move your orders.</span></h2><p>Choose a partner from the Bucket India pool or switch to API mode for your own shipping account.</p></div><div className="shipping-security"><ShieldCheck size={20}/><b>Credentials protected</b><small>Only masked credential hints are retained in the workspace.</small></div></section>
  <div className="shipping-workspace"><Card className="shipping-provider-card"><Head kicker="STEP 1 · CHOOSE PARTNER" title="Shipping partner pool"/><div className="shipping-provider-grid">{providers.map(p=><button className={provider===p.id?"active":""} onClick={()=>setProvider(p.id)} key={p.id}><span>{p.icon}</span><div><b>{p.name}</b><small>{p.desc}</small></div><em>{p.tag}</em>{active?.enabled&&<CheckCircle size={16}/>}</button>)}</div></Card>
  <Card className="shipping-connect-card"><Head kicker="STEP 2 · CONNECTION" title={providers.find(x=>x.id===provider)?.name||"Shipping partner"} text="Use the pool connection or provide your own API credentials."/><div className="shipping-mode-toggle"><button className={mode==="pool"?"active":""} onClick={()=>setMode("pool")}>Connect from pool</button><button className={mode==="api"?"active":""} onClick={()=>setMode("api")}><Key size={14}/> Use API keys</button></div>{mode==="pool"?<div className="shipping-pool-connect"><div className="pool-icon"><PlugsConnected size={26}/></div><div><b>Managed connection</b><p>Bucket India handles the connection profile. No API key is required in this workspace.</p></div></div>:<div className="shipping-api-form"><label>Account label<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="My Shiprocket account"/></label><label>API key<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Paste API key"/></label><label>API secret / token<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Paste secret"/></label><div className="shipping-secret-note"><ShieldCheck size={15}/> Keys are never displayed again; only last-four hints are retained. Use a server-side integration endpoint for live courier calls.</div></div>}<button className="btn primary full" disabled={busy} onClick={connect}>{busy?"Saving connection…":"Save shipping connection"} <ArrowRight size={15}/></button>{msg&&<div className="alert success">{msg}</div>}</Card></div>
  <Card><Head kicker="CONNECTED" title="Your shipping network"/>{d.shipping.length?<div className="connected-shipping-list">{d.shipping.map(s=><div key={s.id}><span className="provider-mark">{(providers.find(p=>p.id===s.provider)?.icon||"S")}</span><div><b>{providers.find(p=>p.id===s.provider)?.name||s.provider}</b><small>{s.connection_mode==="api"?"API connection":"Managed pool"} · {s.account_label||"Default account"}{s.api_key_last4?" · API ••••"+s.api_key_last4:""}</small></div><span className="status-pill delivered">{s.enabled?"Connected":"Disabled"}</span></div>)}</div>:<Empty title="No shipping partner connected" text="Choose a carrier above to start your fulfillment setup."/ >}</Card>
 </AppShell>
}

export function VendorAnalytics(){
 const d=useVendorData(); const [from,setFrom]=useState(""),[to,setTo]=useState("");
 const rows=useMemo(()=>d.orders.filter(o=>(!from||o.created_at.slice(0,10)>=from)&&(!to||o.created_at.slice(0,10)<=to)),[d.orders,from,to]);
 const gmv=rows.reduce((a,o)=>a+Number(o.amount||0),0),del=rows.filter(o=>o.status==="delivered").length,rto=rows.filter(o=>o.status==="rto").length,ndr=rows.filter(o=>o.status==="ndr").length;
 const productMap={};rows.forEach(o=>{const p=o.listing_id||o.external_order_id||o.id;productMap[p]=(productMap[p]||0)+Number(o.amount||0)});
 const top=d.products.map(p=>({p,value:rows.filter(o=>o.vendor_id===d.vendor?.id && (o.listing_id===p.id||String(o.external_order_id||"").includes(p.sku||"@@"))).reduce((a,o)=>a+Number(o.amount||0),0)})).sort((a,b)=>b.value-a.value).slice(0,5);
 return <AppShell role="vendor" title="Analytics">
  <section className="vendor-analytics-hero"><div><span className="hero-kicker">VENDOR INTELLIGENCE</span><h2>See what is moving, <span>not just what is listed.</span></h2><p>Track demand, GMV, delivery outcomes, RTO exposure and catalog movement from one live view.</p></div><ChartLineUp size={72}/></section>
  <Card className="vendor-analytics-filters"><div><span className="section-kicker">FILTER ANALYTICS</span><b>Date range</b></div><label><CalendarBlank size={14}/> From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><span>→</span><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn secondary" onClick={()=>{setFrom("");setTo("")}}><Funnel size={13}/> Reset</button></Card>
  <div className="stats modern-stats"><Stat label="GMV" value={money(gmv)} hint={rows.length+" orders"}/><Stat label="Delivered" value={del} hint={rows.length?Math.round(del/rows.length*100)+"% delivery":"—"}/><Stat label="NDR" value={ndr} hint="Active exceptions"/><Stat label="RTO" value={rto} hint={rows.length?Math.round(rto/rows.length*100)+"% of orders":"—"}/></div>
  <div className="vendor-analytics-grid"><Card><Head kicker="ORDER MIX" title="Fulfillment distribution"/><div className="vendor-bar-chart">{statuses.map(s=>{const n=rows.filter(o=>o.status===s).length;return <div key={s}><b>{n}</b><i style={{height:Math.max(7,rows.length?n/rows.length*100:7)+"%"}}/><span>{s}</span></div>})}</div></Card><Card><Head kicker="CATALOG SIGNAL" title="Top product movement"/>{top.length?<div className="vendor-top-products">{top.map(x=><div key={x.p.id}><span>{x.p.image_url?<img src={x.p.image_url} alt=""/>:<Package/>}</span><div><b>{x.p.title}</b><small>{x.p.stock||0} stock · RTO {money(x.p.rto_charge)}</small></div><strong>{money(x.value)}</strong></div>)}</div>:<Empty title="Product analytics will build here" text="Orders linked to your catalog will populate this view."/ >}</Card></div>
  <Card><Head kicker="OPERATIONAL INSIGHTS" title="What needs attention"/><div className="vendor-insight-grid"><div><WarningCircle size={18}/><b>{d.products.filter(p=>Number(p.stock||0)<10).length} low-stock SKUs</b><span>Protect seller availability before inventory becomes a missed order.</span></div><div><Truck size={18}/><b>{rto} RTO orders</b><span>Review product-level RTO charge and delivery performance.</span></div><div><UsersThree size={18}/><b>{new Set(rows.map(o=>o.seller_id).filter(Boolean)).size} seller accounts</b><span>Monitor which sellers are generating repeat demand.</span></div></div></Card>
 </AppShell>
}

export function VendorSettings(){
 const {session,profile}=useAuth(); const d=useVendorData(); const [form,setForm]=useState({business_name:"",gstin:"",gst_legal_name:"",bank_account_name:"",bank_account_number:"",bank_ifsc:"",bank_name:"",billing_address:{line1:"",line2:"",city:"",state:"",pincode:"",country:"India"},default_shipping_provider:"",default_shipping_mode:"standard",notify_new_orders:true,notify_low_stock:true,notify_ndr:true,notify_rto:true}); const [msg,setMsg]=useState(""),[kyc,setKyc]=useState(null),[saving,setSaving]=useState(false);
 useEffect(()=>{if(!session?.user?.id)return;(async()=>{const [{data:s},{data:k}]=await Promise.all([supabase.from("vendor_settings").select("*").eq("user_id",session.user.id).maybeSingle(),supabase.from("kyc_profiles").select("status,completion").eq("user_id",session.user.id).maybeSingle()]);if(s)setForm(x=>({...x,...s,billing_address:{...x.billing_address,...(s.billing_address||{})}}));setKyc(k||null)})()},[session?.user?.id]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));const setA=(k,v)=>setForm(x=>({...x,billing_address:{...x.billing_address,[k]:v}}));
 async function save(e){e.preventDefault();if(!session?.user?.id)return;setSaving(true);const payload={...form,user_id:session.user.id,updated_at:new Date().toISOString(),gst_legal_name:form.gst_legal_name||form.business_name};const {error}=await supabase.from("vendor_settings").upsert(payload,{onConflict:"user_id"});setSaving(false);setMsg(error?error.message:"Vendor settings saved.");}
 async function changePassword(){const p=prompt("Enter a new password (minimum 8 characters):");if(!p||p.length<8)return alert("Use at least 8 characters.");const {error}=await supabase.auth.updateUser({password:p});alert(error?error.message:"Password updated.");}
 return <AppShell role="vendor" title="Settings">
  <section className="vendor-settings-hero"><div><span className="hero-kicker">VENDOR CONTROL CENTER</span><h2>Business, money and <span>account control.</span></h2><p>Keep your KYC, billing, bank, shipping defaults, alerts and account security together.</p></div><div><span className="settings-status-dot"/> {profile?.full_name||"Vendor account"}</div></section>
  <form onSubmit={save}><div className="vendor-settings-grid">
   <Card><Head kicker="BUSINESS IDENTITY" title="Vendor account" text="The business identity sellers see across the supply network."/><label>Business name<input value={form.business_name||d.vendor?.business_name||""} onChange={e=>set("business_name",e.target.value)} placeholder="Your business name"/></label><label>GSTIN<input value={form.gstin||""} onChange={e=>set("gstin",e.target.value.toUpperCase())} placeholder="22AAAAA0000A1Z5"/></label><label>Legal name<input value={form.gst_legal_name||""} onChange={e=>set("gst_legal_name",e.target.value)} placeholder="Legal entity name"/></label></Card>
   <Card><Head kicker="KYC" title="Verification status" action={<NavLink className="btn compact secondary" to="/vendor/kyc">Open KYC</NavLink>}/><div className="vendor-kyc-box"><div><ShieldCheck size={25}/><b>{kyc?.status==="verified"?"Verified":kyc?.status==="submitted"?"Under review":"Complete your KYC"}</b><span>{kyc?.completion||0}% complete</span></div><i><em style={{width:(kyc?.completion||0)+"%"}}/></i></div></Card>
   <Card><Head kicker="BILLING" title="Business billing address" text="Used for invoices, documents and account records."/><div className="form-row"><label>Address<input value={form.billing_address.line1} onChange={e=>setA("line1",e.target.value)} placeholder="Street / building"/></label><label>Area<input value={form.billing_address.line2} onChange={e=>setA("line2",e.target.value)} placeholder="Area / landmark"/></label></div><div className="form-row"><label>City<input value={form.billing_address.city} onChange={e=>setA("city",e.target.value)}/></label><label>State<input value={form.billing_address.state} onChange={e=>setA("state",e.target.value)}/></label></div><div className="form-row"><label>Pincode<input value={form.billing_address.pincode} onChange={e=>setA("pincode",e.target.value)}/></label><label>Country<input value={form.billing_address.country} onChange={e=>setA("country",e.target.value)}/></label></div></Card>
   <Card><Head kicker="BANK & PAYOUTS" title="Settlement bank account" text="Keep the account used for eligible vendor settlements."/><div className="form-row"><label>Account holder<input value={form.bank_account_name||""} onChange={e=>set("bank_account_name",e.target.value)}/></label><label>Bank name<input value={form.bank_name||""} onChange={e=>set("bank_name",e.target.value)}/></label></div><div className="form-row"><label>Account number<input type="password" value={form.bank_account_number||""} onChange={e=>set("bank_account_number",e.target.value)}/></label><label>IFSC<input value={form.bank_ifsc||""} onChange={e=>set("bank_ifsc",e.target.value.toUpperCase())}/></label></div><div className="settings-verification pending">○ Bank verification pending<small>Connect verification before withdrawals are enabled.</small></div></Card>
   <Card><Head kicker="FULFILLMENT DEFAULTS" title="Shipping preferences"/><div className="form-row"><label>Default shipping partner<select value={form.default_shipping_provider||""} onChange={e=>set("default_shipping_provider",e.target.value)}><option value="">Choose later</option>{providers.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Default mode<select value={form.default_shipping_mode} onChange={e=>set("default_shipping_mode",e.target.value)}><option value="standard">Standard</option><option value="express">Express</option></select></label></div><NavLink className="btn secondary" to="/vendor/shipping"><Truck size={15}/> Manage shipping partners</NavLink></Card>
   <Card><Head kicker="NOTIFICATIONS" title="Operational alerts"/><div className="vendor-toggle-list">{[["notify_new_orders","New seller orders","Know when a new order needs fulfillment."],["notify_low_stock","Low stock","Get alerted before inventory becomes a seller problem."],["notify_ndr","NDR","Know when delivery needs recovery."],["notify_rto","RTO","Track returns before they become a recurring cost."]].map(([k,t,x])=><label key={k}><span><b>{t}</b><small>{x}</small></span><input type="checkbox" checked={!!form[k]} onChange={e=>set(k,e.target.checked)}/><i/></label>)}</div></Card>
   <Card><Head kicker="ACCOUNT SECURITY" title="Account controls"/><div className="vendor-security-row"><div><Key size={20}/><b>Password</b><small>Update your sign-in password.</small></div><button type="button" className="btn secondary" onClick={changePassword}>Change password</button></div><div className="vendor-security-row"><div><Gear size={20}/><b>Vendor status</b><small>{d.vendor?.status||"Account"} · Owner account connected.</small></div><span className="status-pill delivered">Active</span></div></Card>
  </div><div className="settings-savebar"><div><b>Vendor workspace settings</b><span>Saved to your vendor account.</span></div><button className="btn primary" disabled={saving}>{saving?"Saving…":"Save all settings"}</button></div></form>{msg&&<div className="settings-alert success">{msg}</div>}
 </AppShell>
}
