import {NavLink,useLocation,useNavigate} from "react-router-dom";
import {useEffect,useMemo,useState} from "react";
import {Bell,SignOut,House,ChartLine,SquaresFour,PlusSquare,Package,Truck,WarningCircle,Wallet,Receipt,Storefront,Gear,Sun,Moon,MagnifyingGlass,X,Command,Clock,CheckCircle,ShoppingCart,UsersThree} from "@phosphor-icons/react";
import {useAuth} from "../context/AuthContext";

const iconMap={Home:House,Overview:House,Analytics:ChartLine,Reports:ChartLine,"Business Health":ChartLine,"Product Marketplace":SquaresFour,"My Catalog":Package,Products:Package,"Import Products":PlusSquare,Inventory:Package,Orders:ShoppingCart,Shipments:Truck,Shipping:Truck,NDR:WarningCircle,"NDR & RTO":WarningCircle,Wallet:Wallet,Settlements:Receipt,"Shopify Stores":Storefront,Stores:Storefront,Settings:Gear,Sellers:UsersThree,Pricing:Receipt,KYC:CheckCircle,Integrations:SquaresFour};
const sellerGroups=[{title:"Command Center",items:[["Home","/seller"],["Analytics","/seller/analytics"]]},{title:"Sell",items:[["Product Marketplace","/seller/products"],["My Catalog","/seller/catalog"]]},{title:"Orders",items:[["Orders","/seller/orders"],["Shipments","/seller/shipping"],["NDR","/seller/ndr"]]},{title:"Money",items:[["Wallet","/seller/wallet"],["Settlements","/seller/billing"]]},{title:"Channels & Account",items:[["Shopify Stores","/seller/stores"],["Settings","/seller/settings"]]}];
const vendorGroups=[{title:"Command Center",items:[["Overview","/vendor"],["Analytics","/vendor/analytics"],["Reports","/vendor/reports"],["Business Health","/vendor/health"]]},{title:"Catalog",items:[["Products","/vendor/products"],["Import Products","/vendor/import"],["Inventory","/vendor/inventory"]]},{title:"Orders & Fulfillment",items:[["Orders","/vendor/orders"],["Shipping","/vendor/shipping"],["NDR & RTO","/vendor/exceptions"]]},{title:"Business",items:[["Sellers","/vendor/sellers"],["Wallet","/vendor/wallet"],["Pricing","/vendor/pricing"]]},{title:"Account",items:[["KYC","/vendor/kyc"],["Integrations","/vendor/shipping"],["Settings","/vendor/settings"]]}];

function SearchPalette({open,onClose,role}){const [q,setQ]=useState("");const navigate=useNavigate();const groups=role==="vendor"?vendorGroups:sellerGroups;const items=useMemo(()=>groups.flatMap(g=>g.items.map(([label,href])=>({label,href,group:g.title}))),[groups]);const results=items.filter(x=>x.label.toLowerCase().includes(q.toLowerCase())||x.group.toLowerCase().includes(q.toLowerCase())).slice(0,8);useEffect(()=>{if(!open)return;const f=e=>{if(e.key==="Escape")onClose()};window.addEventListener("keydown",f);return()=>window.removeEventListener("keydown",f)},[open,onClose]);if(!open)return null;return <div className="search-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="search-dialog"><div className="search-dialog-input"><MagnifyingGlass size={19}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products, orders, tools..." /><kbd>ESC</kbd><button onClick={onClose}><X size={17}/></button></div><div className="search-results">{results.map(x=>{const I=iconMap[x.label]||SquaresFour;return <button key={x.href} onClick={()=>{navigate(x.href);onClose()}}><I size={18}/><span><b>{x.label}</b><small>{x.group}</small></span><span className="search-arrow">↵</span></button>})}{!results.length&&<div className="search-empty"><MagnifyingGlass size={24}/><b>No matching workspace tools</b><span>Try Orders, Products, NDR or Settings.</span></div>}</div><div className="search-foot"><span><Command/> K to open</span><span>Navigate instantly across your workspace</span></div></div></div>}

function Notifications({open,onClose}){const navigate=useNavigate();const notifications=[{icon:ShoppingCart,title:"Order activity",text:"Review your latest seller orders.",href:"/seller/orders"},{icon:WarningCircle,title:"NDR center",text:"Check delivery exceptions needing action.",href:"/seller/ndr"},{icon:Wallet,title:"Settlement",text:"Review your latest payout activity.",href:"/seller/billing"}];if(!open)return null;return <div className="notification-popover"><div className="notification-head"><div><b>Notifications</b><span>Important workspace activity</span></div><button onClick={onClose}><X size={16}/></button></div>{notifications.map(n=>{const I=n.icon;return <button className="notification-item" key={n.href} onClick={()=>{navigate(n.href);onClose()}}><span className="notification-icon"><I size={17}/></span><span><b>{n.title}</b><small>{n.text}</small></span><span className="notification-dot"/></button>})}<div className="notification-foot">All caught up · Bucket India</div></div>}

export default function AppShell({role,title,children}){
 const {profile,signOut}=useAuth(),navigate=useNavigate(),location=useLocation();const [dark,setDark]=useState(()=>localStorage.getItem("bucket-theme")==="dark"),[searchOpen,setSearchOpen]=useState(false),[notificationsOpen,setNotificationsOpen]=useState(false);
 const groups=role==="vendor"?vendorGroups:sellerGroups;
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("bucket-theme",dark?"dark":"light")},[dark]);
 useEffect(()=>{const f=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setSearchOpen(true)}if(e.key==="Escape"){setSearchOpen(false);setNotificationsOpen(false)}};window.addEventListener("keydown",f);return()=>window.removeEventListener("keydown",f)},[]);
 async function logout(){await signOut();navigate("/login",{replace:true})}
 return <div className="app-shell"><aside className="sidebar"><div className="logo"><span className="logo-mark">B</span><div><strong>Bucket India</strong><small>{role==="vendor"?"Vendor Console":"B2B Marketplace"}</small></div></div><div className="sidebar-scroll">{groups.map(group=><div className="nav-group" key={group.title}><span className="nav-group-title">{group.title}</span><nav>{group.items.map(([label,href],i)=>{const I=iconMap[label]||SquaresFour;return <NavLink key={label} to={href} end={i===0&&href==="/"+role}><I weight="duotone" className="nav-icon"/><span>{label}</span>{label==="Orders"&&<em className="nav-badge">NEW</em>}</NavLink>})}</nav></div>)}</div><div className="sidebar-footer"><div className="avatar">{(profile?.full_name||profile?.role||"U").slice(0,1).toUpperCase()}</div><div className="user-meta"><b>{profile?.full_name||"Account"}</b><span>{profile?.role||role}</span></div><button className="theme-toggle" onClick={()=>setDark(v=>!v)} aria-label="Toggle theme">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-btn" onClick={logout} aria-label="Sign out"><SignOut size={18}/></button></div></aside><main className="main"><header className="topbar"><div className="topbar-title"><div className="eyebrow">{role==="vendor"?"Vendor workspace":"Seller workspace"}</div><h1>{title}</h1></div><div className="topbar-actions"><button className="command-search" onClick={()=>setSearchOpen(true)} aria-label="Open workspace search"><MagnifyingGlass size={18}/><span>Search products, orders, tools...</span><kbd>⌘ K</kbd></button><div className="notification-wrap"><button className={"notification-btn"+(notificationsOpen?" active":"")} onClick={()=>setNotificationsOpen(v=>!v)} title="Notifications" aria-label="Notifications"><Bell size={19} weight={notificationsOpen?"fill":"regular"}/><span>3</span></button><Notifications open={notificationsOpen} onClose={()=>setNotificationsOpen(false)}/></div><span className="online-pill"><i/> Online</span></div></header><SearchPalette open={searchOpen} onClose={()=>setSearchOpen(false)} role={role}/><div className="page">{children}</div></main></div>;
}
export function Stat({label,value,hint}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong>{hint&&<small>{hint}</small>}</div>}
export function Empty({title,text}){return <div className="empty"><div className="empty-icon"><Package size={25}/></div><h3>{title}</h3><p>{text}</p></div>}
